/**
 * GUIKit Project Chooser Script
 * 
 * This script runs on the ESP8266 to handle the project chooser GUI.
 * It scans the /gui/ directory for .GUIKIT projects and dynamically
 * populates the chooser interface.
 */

// ============================================================================
// Global State
// ============================================================================

var ChooserState = {
    projects: [],           // List of available projects
    selectedIndex: -1,      // Currently selected project index
    selectedProject: null,  // Currently selected project name
    defaultProject: '',     // Project set as default in config
    config: null            // Loaded configuration
};

// ============================================================================
// Project Discovery
// ============================================================================

/**
 * Scan the /gui/ directory for .GUIKIT projects
 */
function scanProjects() {
    var projects = [];
    
    // On ESP8266, this would use the SD library to list directories
    // For this implementation, we'll use the GUIKit config library
    
    // Try to use the native file system access
    if (typeof GUIKitFS !== 'undefined') {
        var dirs = GUIKitFS.list('/gui');
        for (var i = 0; i < dirs.length; i++) {
            if (dirs[i].isDirectory && dirs[i].name.endsWith('.GUIKIT')) {
                var projectName = dirs[i].name.replace('.GUIKIT', '');
                projects.push({
                    name: projectName,
                    fullName: dirs[i].name,
                    path: '/gui/' + dirs[i].name,
                    hasMainGUI: GUIKitFS.exists('/gui/' + dirs[i].name + '/main_gui.json'),
                    metadata: loadProjectMetadata('/gui/' + dirs[i].name + '/project.meta.json')
                });
            }
        }
    }
    
    return projects;
}

/**
 * Load project metadata if available
 */
function loadProjectMetadata(path) {
    try {
        if (typeof GUIKitFS !== 'undefined') {
            var content = GUIKitFS.readFile(path);
            if (content) {
                return JSON.parse(content);
            }
        }
    } catch (e) {
        // Metadata not available
    }
    return null;
}

/**
 * Load configuration from /etc/guikitloader.conf
 */
function loadConfig() {
    if (typeof GUIKitConfig !== 'undefined') {
        return GUIKitConfig.load();
    }
    
    // Fallback: try to parse config file directly
    try {
        if (typeof GUIKitFS !== 'undefined') {
            var content = GUIKitFS.readFile('/etc/guikitloader.conf');
            if (content) {
                return parseConfig(content);
            }
        }
    } catch (e) {
        // Config not available
    }
    
    return {
        default_gui: '',
        gui_path: '/gui',
        use_project_dirs: true,
        auto_load_last: true,
        last_gui: ''
    };
}

/**
 * Parse configuration file content
 */
function parseConfig(content) {
    var config = {
        default_gui: '',
        gui_path: '/gui',
        use_project_dirs: true,
        auto_load_last: true,
        last_gui: ''
    };
    
    var lines = content.split('\n');
    for (var i = 0; i < lines.length; i++) {
        var line = lines[i].trim();
        if (!line || line.startsWith('#')) continue;
        
        var equalsIndex = line.indexOf('=');
        if (equalsIndex === -1) continue;
        
        var key = line.substring(0, equalsIndex).trim();
        var value = line.substring(equalsIndex + 1).trim();
        
        switch (key) {
            case 'default_gui':
                config.default_gui = value;
                break;
            case 'gui_path':
                config.gui_path = value;
                break;
            case 'use_project_dirs':
                config.use_project_dirs = value.toLowerCase() === 'true';
                break;
            case 'auto_load_last':
                config.auto_load_last = value.toLowerCase() === 'true';
                break;
            case 'last_gui':
                config.last_gui = value;
                break;
        }
    }
    
    return config;
}

/**
 * Save configuration to /etc/guikitloader.conf
 */
function saveConfig(config) {
    if (typeof GUIKitConfig !== 'undefined') {
        return GUIKitConfig.save(config);
    }
    
    // Fallback: write directly
    if (typeof GUIKitFS !== 'undefined') {
        var content = generateConfig(config);
        GUIKitFS.writeFile('/etc/guikitloader.conf', content);
        return true;
    }
    
    return false;
}

/**
 * Generate configuration file content
 */
function generateConfig(config) {
    var lines = [];
    lines.push('# GUIKit Configuration');
    lines.push('# Generated by GUIKit Chooser');
    lines.push('');
    lines.push('default_gui=' + (config.default_gui || ''));
    lines.push('gui_path=' + (config.gui_path || '/gui'));
    lines.push('use_project_dirs=' + (config.use_project_dirs ? 'true' : 'false'));
    lines.push('auto_load_last=' + (config.auto_load_last ? 'true' : 'false'));
    lines.push('last_gui=' + (config.last_gui || ''));
    return lines.join('\n');
}

// ============================================================================
// GUI Initialization
// ============================================================================

/**
 * Initialize the chooser
 */
function init_chooser() {
    ChooserState.config = loadConfig();
    ChooserState.defaultProject = ChooserState.config.default_gui || '';
    
    // Update default indicator
    updateDefaultIndicator();
    
    // Scan for projects
    refreshProjects();
}

/**
 * Refresh the list of projects
 */
function refresh_projects() {
    refreshProjects();
}

/**
 * Internal: Refresh projects list
 */
function refreshProjects() {
    ChooserState.projects = scanProjects();
    ChooserState.selectedIndex = -1;
    ChooserState.selectedProject = null;
    
    // Clear existing project buttons
    var projectsList = GUI.getWidgetById('projects_list');
    if (projectsList) {
        projectsList.children = [];
    }
    
    // Create buttons for each project
    var y = 5;
    for (var i = 0; i < ChooserState.projects.length; i++) {
        var project = ChooserState.projects[i];
        
        // Skip if no main_gui.json
        if (!project.hasMainGUI) continue;
        
        var btnY = y + (i * 30);
        
        var projectBtn = {
            id: 'project_' + i,
            type: 'button',
            x: 5,
            y: btnY,
            width: 220,
            height: 25,
            text: project.name + (project.name === ChooserState.defaultProject ? ' ★' : ''),
            text_color: '#FFFFFF',
            background: '#2D2D2D',
            border_color: '#3E3E42',
            border_width: 1,
            text_size: 12,
            text_align: 'left',
            action: 'select_project',
            data: { index: i }
        };
        
        // Add description if available
        if (project.metadata && project.metadata.description) {
            projectBtn.text = project.name + ' - ' + project.metadata.description.substring(0, 30);
        }
        
        projectsList.children.push(projectBtn);
    }
    
    // Update info text
    var infoText = GUI.getWidgetById('info_text');
    if (infoText) {
        infoText.text = ChooserState.projects.length + ' project(s) found';
    }
    
    // Disable load/set default buttons
    disableActionButtons();
    
    // Request GUI redraw
    GUI.redraw();
}

/**
 * Update the default project indicator
 */
function updateDefaultIndicator() {
    var defaultIndicator = GUI.getWidgetById('default_indicator');
    if (defaultIndicator) {
        defaultIndicator.text = 'Default: ' + (ChooserState.defaultProject || 'NONE');
    }
}

/**
 * Disable action buttons
 */
function disableActionButtons() {
    var loadBtn = GUI.getWidgetById('load_btn');
    var setDefaultBtn = GUI.getWidgetById('set_default_btn');
    
    if (loadBtn) loadBtn.disabled = ChooserState.selectedIndex === -1;
    if (setDefaultBtn) setDefaultBtn.disabled = ChooserState.selectedIndex === -1;
}

// ============================================================================
// Project Selection
// ============================================================================

/**
 * Select a project from the list
 */
function select_project(widget, event) {
    if (widget.data && widget.data.index !== undefined) {
        var index = widget.data.index;
        
        // Clear previous selection
        for (var i = 0; i < ChooserState.projects.length; i++) {
            var btn = GUI.getWidgetById('project_' + i);
            if (btn) {
                btn.background = '#2D2D2D';
                btn.border_color = '#3E3E42';
            }
        }
        
        // Select new project
        ChooserState.selectedIndex = index;
        ChooserState.selectedProject = ChooserState.projects[index].name;
        
        var selectedBtn = GUI.getWidgetById('project_' + index);
        if (selectedBtn) {
            selectedBtn.background = '#0078D4';
            selectedBtn.border_color = '#005A9E';
        }
        
        // Enable action buttons
        var loadBtn = GUI.getWidgetById('load_btn');
        var setDefaultBtn = GUI.getWidgetById('set_default_btn');
        
        if (loadBtn) loadBtn.disabled = false;
        if (setDefaultBtn) setDefaultBtn.disabled = false;
        
        // Update info text
        var infoText = GUI.getWidgetById('info_text');
        if (infoText) {
            var project = ChooserState.projects[index];
            infoText.text = 'Selected: ' + project.name + 
                (project.metadata && project.metadata.version ? ' v' + project.metadata.version : '');
        }
        
        GUI.redraw();
    }
}

/**
 * Load the selected project
 */
function load_selected_project(widget, event) {
    if (ChooserState.selectedIndex === -1 || !ChooserState.selectedProject) {
        return;
    }
    
    var project = ChooserState.projects[ChooserState.selectedIndex];
    
    // On ESP8266, this would trigger loading the project's main_gui.json
    if (typeof GUIKitLoader !== 'undefined') {
        GUIKitLoader.loadProject(project.name);
    } else {
        // Fallback: try to load via config
        var config = ChooserState.config;
        config.last_gui = project.name;
        saveConfig(config);
        
        // Reload with the new project
        if (typeof System !== 'undefined') {
            System.reboot(); // Reboot to load new GUI
        }
    }
}

/**
 * Set the selected project as default
 */
function set_as_default(widget, event) {
    if (ChooserState.selectedIndex === -1 || !ChooserState.selectedProject) {
        return;
    }
    
    var config = ChooserState.config;
    config.default_gui = ChooserState.selectedProject;
    
    if (saveConfig(config)) {
        ChooserState.defaultProject = ChooserState.selectedProject;
        updateDefaultIndicator();
        refreshProjects(); // Refresh to show the star marker
        
        // Update info text
        var infoText = GUI.getWidgetById('info_text');
        if (infoText) {
            infoText.text = 'Default set to: ' + ChooserState.selectedProject;
        }
    } else {
        // Show error
        var infoText = GUI.getWidgetById('info_text');
        if (infoText) {
            infoText.text = 'Error: Failed to save config';
        }
    }
    
    GUI.redraw();
}

// ============================================================================
// Direct Project Loading
// ============================================================================

/**
 * Load a project directly by name (used by kernel on boot)
 */
function loadProject(projectName) {
    var config = loadConfig();
    
    // Build path
    var path = config.gui_path + '/' + projectName + '.GUIKIT/main_gui.json';
    
    // On ESP8266, this would load the GUI from SD card
    if (typeof GUIKitFS !== 'undefined') {
        var content = GUIKitFS.readFile(path);
        if (content) {
            var gui = JSON.parse(content);
            GUI.load(gui);
            
            // Update last_gui if auto_load_last is enabled
            if (config.auto_load_last) {
                config.last_gui = projectName;
                saveConfig(config);
            }
            
            return true;
        }
    }
    
    return false;
}

// ============================================================================
// Default Loading (Kernel Entry Point)
// ============================================================================

/**
 * This function is called by kernel.bin on boot
 * It loads the default GUI based on configuration
 */
function loadDefaultGUI() {
    var config = loadConfig();
    
    // If default_gui is set and use_project_dirs is true
    if (config.default_gui && config.use_project_dirs) {
        if (loadProject(config.default_gui)) {
            return true;
        }
    }
    
    // Fallback: try last_gui
    if (config.last_gui && config.auto_load_last && config.use_project_dirs) {
        if (loadProject(config.last_gui)) {
            return true;
        }
    }
    
    // Final fallback: try /gui/main_gui.json
    if (typeof GUIKitFS !== 'undefined') {
        var fallbackPath = '/gui/main_gui.json';
        if (GUIKitFS.exists(fallbackPath)) {
            var content = GUIKitFS.readFile(fallbackPath);
            if (content) {
                var gui = JSON.parse(content);
                GUI.load(gui);
                return true;
            }
        }
    }
    
    // If all else fails, load the chooser itself
    return loadProject('chooser');
}

// ============================================================================
// Export for ESP8266 Integration
// ============================================================================

// These functions are available to the ESP8266 kernel
var GUIKitChooser = {
    init: init_chooser,
    refresh: refreshProjects,
    loadDefault: loadDefaultGUI,
    loadProject: loadProject,
    scanProjects: scanProjects,
    getSelected: function() { return ChooserState.selectedProject; },
    getProjects: function() { return ChooserState.projects; },
    setDefault: function(projectName) {
        var config = ChooserState.config;
        config.default_gui = projectName;
        ChooserState.defaultProject = projectName;
        return saveConfig(config);
    }
};

// Make available globally
if (typeof window !== 'undefined') {
    window.GUIKitChooser = GUIKitChooser;
}
if (typeof global !== 'undefined') {
    global.GUIKitChooser = GUIKitChooser;
}
