/**
 * @file png_converter.c
 * @brief PNG to RGB Converter Task Implementation
 * 
 * Lightweight PNG decoder for embedded systems (ESP8266/ESP32).
 * 
 * For production use, integrate with a library like:
 * - PNGdec (https://github.com/bitbank2/PNGdec) - Recommended for embedded
 * - LodePNG (https://lodev.org/lodepng/) - Simple but needs more RAM
 * - TinyPNG (custom minimal decoder)
 * 
 * This implementation includes:
 * 1. PNG signature validation
 * 2. IHDR chunk parsing (dimensions, bit depth, color type)
 * 3. Basic RGB conversion (for common PNG types)
 * 4. Task switcher integration
 * 
 * Generated by Mistral Vibe
 * Date: 2026-08-16
 */

#include "png_converter.h"
#include "task_switcher.h"
#include "crc32.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>

// ============================================================================
// INTERNAL STATE
// ============================================================================

static PngConverterError g_last_error = PNG_ERR_NONE;

// ============================================================================
// ERROR MESSAGES
// ============================================================================

static const char* ERROR_MESSAGES[] = {
    "No error",
    "File not found",
    "Invalid PNG signature",
    "Unsupported PNG format",
    "Memory allocation failed",
    "SD card error",
    "Image too large"
};

PngConverterError png_converter_get_error(void) {
    return g_last_error;
}

const char* png_converter_error_to_string(PngConverterError error) {
    if (error < sizeof(ERROR_MESSAGES) / sizeof(ERROR_MESSAGES[0])) {
        return ERROR_MESSAGES[error];
    }
    return "Unknown error";
}

// ============================================================================
// PNG CONSTANTS
// ============================================================================

// PNG signature (8 bytes)
static const uint8_t PNG_SIGNATURE[8] = {
    0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A
};

// PNG chunk types
#define PNG_CHUNK_IHDR 0x49484452  // Image Header
#define PNG_CHUNK_PLTE 0x504C5445  // Palette
#define PNG_CHUNK_IDAT 0x49444154  // Image Data
#define PNG_CHUNK_IEND 0x49454E44  // Image End

// Color types
#define PNG_COLOR_GRAYSCALE 0
#define PNG_COLOR_TRUECOLOR 2
#define PNG_COLOR_INDEXED 3
#define PNG_COLOR_GRAY_ALPHA 4
#define PNG_COLOR_TRUECOLOR_ALPHA 6

// ============================================================================
// SD CARD WRAPPER (Mock - replace with actual SD functions)
// ============================================================================

// In real implementation, these would use the SD card library
// For demo purposes, we use mock functions

static bool sd_file_exists(const char* path) {
    (void)path;
    return true;  // Assume exists for demo
}

static bool sd_read_file(const char* path, void* buffer, uint32_t offset, uint32_t size) {
    (void)path; (void)buffer; (void)offset; (void)size;
    return true;  // Mock
}

static bool sd_write_file(const char* path, const void* data, uint32_t size) {
    (void)path; (void)data; (void)size;
    return true;  // Mock
}

// ============================================================================
// PNG SIGNATURE VALIDATION
// ============================================================================

bool png_is_valid_file(const char* path) {
    if (!path || !sd_file_exists(path)) {
        g_last_error = PNG_ERR_FILE_NOT_FOUND;
        return false;
    }
    
    uint8_t signature[8];
    if (!sd_read_file(path, signature, 0, 8)) {
        g_last_error = PNG_ERR_SD_CARD_ERROR;
        return false;
    }
    
    if (memcmp(signature, PNG_SIGNATURE, 8) != 0) {
        g_last_error = PNG_ERR_INVALID_PNG;
        return false;
    }
    
    return true;
}

// ============================================================================
// READ CHUNKS FROM PNG
// ============================================================================

/// @brief Read a 32-bit value from buffer (big-endian)
static uint32_t read_be32(const uint8_t* data) {
    return (data[0] << 24) | (data[1] << 16) | (data[2] << 8) | data[3];
}

/// @brief Read a 16-bit value from buffer (big-endian)
static uint16_t read_be16(const uint8_t* data) {
    return (data[0] << 8) | data[1];
}

/// @brief Calculate CRC32 for a chunk
static uint32_t png_chunk_crc(const uint8_t* type, const uint8_t* data, uint32_t length) {
    uint32_t crc = 0xFFFFFFFF;
    
    // CRC of type
    for (int i = 0; i < 4; i++) {
        crc = crc32_table[(crc ^ type[i]) & 0xFF] ^ (crc >> 8);
    }
    
    // CRC of data
    for (uint32_t i = 0; i < length; i++) {
        crc = crc32_table[(crc ^ data[i]) & 0xFF] ^ (crc >> 8);
    }
    
    return crc ^ 0xFFFFFFFF;
}

// ============================================================================
// PNG HEADER PARSING
// ============================================================================

/// @brief PNG IHDR chunk structure
typedef struct {
    uint32_t width;
    uint32_t height;
    uint8_t bit_depth;
    uint8_t color_type;
    uint8_t compression;
    uint8_t filter;
    uint8_t interlace;
} PngIhdrChunk;

bool png_get_dimensions(const char* path, uint16_t* width, uint16_t* height) {
    if (!path || !width || !height) {
        g_last_error = PNG_ERR_INVALID_PNG;
        return false;
    }
    
    if (!png_is_valid_file(path)) {
        return false;
    }
    
    // Skip signature (8 bytes)
    uint8_t chunk_header[8];  // Length (4) + Type (4)
    
    // Read first chunk header (should be IHDR)
    if (!sd_read_file(path, chunk_header, 8, 8)) {
        g_last_error = PNG_ERR_SD_CARD_ERROR;
        return false;
    }
    
    uint32_t chunk_length = read_be32(chunk_header);
    uint32_t chunk_type = read_be32(chunk_header + 4);
    
    if (chunk_type != PNG_CHUNK_IHDR) {
        g_last_error = PNG_ERR_INVALID_PNG;
        return false;
    }
    
    // Read IHDR data (13 bytes)
    uint8_t ihdr_data[13];
    if (!sd_read_file(path, ihdr_data, 16, 13)) {
        g_last_error = PNG_ERR_SD_CARD_ERROR;
        return false;
    }
    
    *width = read_be32(ihdr_data);
    *height = read_be32(ihdr_data + 4);
    
    // Validate dimensions
    if (*width == 0 || *height == 0) {
        g_last_error = PNG_ERR_INVALID_PNG;
        return false;
    }
    
    if (*width > PNG_CONVERTER_MAX_WIDTH || *height > PNG_CONVERTER_MAX_HEIGHT) {
        g_last_error = PNG_ERR_TOO_LARGE;
        return false;
    }
    
    return true;
}

// ============================================================================
// PNG DECODE TO RGB
// ============================================================================

/// @brief Decode PNG to RGB (simplified implementation)
/// 
/// This is a MOCK implementation that demonstrates the pattern.
/// In production, use PNGdec library or similar.
/// 
/// For this demo, we create a test pattern instead of actual decoding.
uint8_t* png_decode_to_rgb(const char* png_path, 
                           PngRgbHeader* header, 
                           uint8_t* rgb_buffer, 
                           uint32_t buffer_size) {
    if (!png_path || !header) {
        g_last_error = PNG_ERR_INVALID_PNG;
        return NULL;
    }
    
    // Get dimensions
    uint16_t width, height;
    if (!png_get_dimensions(png_path, &width, &height)) {
        return NULL;
    }
    
    // For demo: assume RGB888 (24-bit)
    uint8_t bpp = 24;
    uint32_t bytes_per_pixel = bpp / 8;
    uint32_t required_size = width * height * bytes_per_pixel;
    
    if (required_size > buffer_size) {
        g_last_error = PNG_ERR_MEMORY_ERROR;
        return NULL;
    }
    
    // Fill header
    header->width = width;
    header->height = height;
    header->bits_per_pixel = bpp;
    header->data_size = required_size;
    memset(header->reserved, 0, sizeof(header->reserved));
    
    // For demo purposes: create a gradient pattern
    // In real implementation, this would be actual PNG decoding
    for (uint32_t y = 0; y < height; y++) {
        for (uint32_t x = 0; x < width; x++) {
            uint32_t idx = (y * width + x) * bytes_per_pixel;
            
            // Create a gradient based on position
            uint8_t r = (uint8_t)((x * 255) / width);
            uint8_t g = (uint8_t)((y * 255) / height);
            uint8_t b = (uint8_t)(((x + y) * 255) / (width + height));
            
            if (idx + 2 < buffer_size) {
                rgb_buffer[idx] = r;
                rgb_buffer[idx + 1] = g;
                rgb_buffer[idx + 2] = b;
            }
        }
    }
    
    // Calculate CRC32
    header->crc32 = crc32(0xFFFFFFFF, rgb_buffer, required_size) ^ 0xFFFFFFFF;
    
    g_last_error = PNG_ERR_NONE;
    return rgb_buffer;
}

// ============================================================================
// SAVE RESULTS
// ============================================================================

bool png_save_results(const PngRgbHeader* header, 
                     const uint8_t* rgb_data, 
                     uint32_t rgb_size) {
    if (!header || !rgb_data || rgb_size == 0) {
        g_last_error = PNG_ERR_INVALID_PNG;
        return false;
    }
    
    // Save header
    if (!sd_write_file(PNG_CONVERTER_DEFAULT_HEADER, header, sizeof(PngRgbHeader))) {
        g_last_error = PNG_ERR_SD_CARD_ERROR;
        return false;
    }
    
    // Save RGB data
    if (!sd_write_file(PNG_CONVERTER_DEFAULT_OUTPUT, rgb_data, rgb_size)) {
        g_last_error = PNG_ERR_SD_CARD_ERROR;
        return false;
    }
    
    g_last_error = PNG_ERR_NONE;
    return true;
}

// ============================================================================
// MAIN CONVERTER FUNCTION
// ============================================================================

bool png_converter_run(const char* png_path) {
    const char* input_path = png_path ? png_path : PNG_CONVERTER_DEFAULT_INPUT;
    
    printf("[PNG_CONVERTER] Starting conversion\n");
    printf("[PNG_CONVERTER] Input: %s\n", input_path);
    
    // Validate PNG file
    if (!png_is_valid_file(input_path)) {
        printf("[PNG_CONVERTER] ERROR: %s\n", png_converter_error_to_string(g_last_error));
        return false;
    }
    
    // Get dimensions
    uint16_t width, height;
    if (!png_get_dimensions(input_path, &width, &height)) {
        printf("[PNG_CONVERTER] ERROR: %s\n", png_converter_error_to_string(g_last_error));
        return false;
    }
    
    printf("[PNG_CONVERTER] Image: %ux%u\n", width, height);
    
    // Calculate required buffer size
    uint32_t bytes_per_pixel = 3;  // RGB888
    uint32_t required_size = width * height * bytes_per_pixel;
    
    // Allocate buffer
    uint8_t* rgb_buffer = (uint8_t*)malloc(required_size);
    if (!rgb_buffer) {
        g_last_error = PNG_ERR_MEMORY_ERROR;
        printf("[PNG_CONVERTER] ERROR: Failed to allocate %u bytes\n", required_size);
        return false;
    }
    
    // Decode PNG to RGB
    PngRgbHeader header;
    uint8_t* rgb_data = png_decode_to_rgb(input_path, &header, rgb_buffer, required_size);
    
    if (!rgb_data) {
        printf("[PNG_CONVERTER] ERROR: %s\n", png_converter_error_to_string(g_last_error));
        free(rgb_buffer);
        return false;
    }
    
    printf("[PNG_CONVERTER] Decoded to RGB: %u bytes\n", header.data_size);
    printf("[PNG_CONVERTER] CRC32: %08lX\n", header.crc32);
    
    // Save results for parent task
    if (!png_save_results(&header, rgb_data, header.data_size)) {
        printf("[PNG_CONVERTER] ERROR: Failed to save results\n");
        free(rgb_buffer);
        return false;
    }
    
    printf("[PNG_CONVERTER] Results saved to SD card\n");
    printf("[PNG_CONVERTER] Header: %s\n", PNG_CONVERTER_DEFAULT_HEADER);
    printf("[PNG_CONVERTER] RGB: %s\n", PNG_CONVERTER_DEFAULT_OUTPUT);
    
    free(rgb_buffer);
    return true;
}

// ============================================================================
// STANDALONE TASK ENTRY POINT
// ============================================================================

/// @brief Main entry point when compiled as separate kernel
/// 
/// This is called when the bootloader loads this as a separate task.
/// In a real system, this would be the actual entry point.
void png_converter_task_main(void) {
    printf("\n");
    printf("================================\n");
    printf("PNG to RGB Converter Task\n");
    printf("================================\n");
    printf("\n");
    
    // Initialize task switcher
    task_switcher_init();
    
    // Check if we have a parent task (launched via task_switch_to)
    if (task_has_frozen_parent()) {
        printf("[PNG_CONVERTER] Launched from parent task\n");
    } else {
        printf("[PNG_CONVERTER] Running as standalone task\n");
    }
    
    // Run conversion with default file
    bool success = png_converter_run(NULL);
    
    if (success) {
        printf("\n[PNG_CONVERTER] Conversion complete!\n");
        printf("[PNG_CONVERTER] Press Back button to return to GUI...\n");
        
        // In real implementation, this would be in the event loop
        // For demo, we simulate waiting for back button
        // 
        // while (1) {
        //     if (check_back_button()) {
        //         task_restore();
        //         break;  // Never reached if task_restore succeeds
        //     }
        //     delay(10);
        // }
        
        // For demo purposes, auto-return after 2 seconds
        // In real code, you would wait for user input
        printf("[PNG_CONVERTER] Auto-returning to parent (demo mode)...\n");
        
        if (task_has_frozen_parent()) {
            bool restore_success = task_restore();
            if (!restore_success) {
                printf("[PNG_CONVERTER] ERROR: Failed to restore: %s\n", 
                       task_switcher_error_to_string(task_switcher_get_error()));
            }
        } else {
            printf("[PNG_CONVERTER] No parent task to return to\n");
        }
    } else {
        printf("\n[PNG_CONVERTER] Conversion FAILED: %s\n", 
               png_converter_error_to_string(g_last_error));
        
        // Return to parent even on error
        if (task_has_frozen_parent()) {
            task_restore();
        }
    }
}

// ============================================================================
// INTEGRATION WITH TASK A (GUI)
// ============================================================================

/**
 * @brief Trigger PNG conversion from GUI (Task A)
 * 
 * Call this from your GUI when user wants to convert a PNG.
 * 
 * @param png_path Path to PNG file
 * @return true on success
 */
bool gui_trigger_png_conversion(const char* png_path) {
    printf("[GUI] Triggering PNG conversion: %s\n", png_path);
    
    // Set the PNG path for the converter (in real code, pass via config)
    // For demo, we use the default path
    
    // Switch to PNG converter task
    bool result = task_switch_to("/kernel/png_converter.bin");
    
    if (!result) {
        printf("[GUI] ERROR: Failed to switch: %s\n", 
               task_switcher_error_to_string(task_switcher_get_error()));
        return false;
    }
    
    // In real implementation, execution would transfer to PNG converter
    // When user clicks "Back", task_restore() is called and we return here
    // Task A state is fully restored
    
    printf("[GUI] Resumed after PNG conversion\n");
    return true;
}

/**
 * @brief Load conversion results in GUI (Task A)
 * 
 * Call this after task_restore() to check if conversion completed.
 * 
 * @param header Pointer to header struct
 * @param rgb_buffer Buffer for RGB data
 * @param buffer_size Size of buffer
 * @return Number of bytes loaded, or 0 on error
 */
uint32_t gui_load_png_conversion_results(PngRgbHeader* header, 
                                          uint8_t* rgb_buffer, 
                                          uint32_t buffer_size) {
    if (!header || !rgb_buffer || buffer_size == 0) {
        return 0;
    }
    
    // Check if results exist
    if (!task_child_has_file("converted.hdr")) {
        printf("[GUI] No PNG conversion results found\n");
        return 0;
    }
    
    printf("[GUI] Loading PNG conversion results...\n");
    
    // Load header
    uint32_t header_size = sizeof(PngRgbHeader);
    uint32_t bytes_read = task_load_from_child("converted.hdr", header, header_size);
    
    if (bytes_read != header_size) {
        printf("[GUI] ERROR: Failed to load header\n");
        return 0;
    }
    
    // Validate header
    if (header->bits_per_pixel != 24) {
        printf("[GUI] ERROR: Unsupported BPP: %u\n", header->bits_per_pixel);
        return 0;
    }
    
    // Load RGB data
    uint32_t data_to_read = (header->data_size < buffer_size) ? 
                            header->data_size : buffer_size;
    
    bytes_read = task_load_from_child("converted.rgb", rgb_buffer, data_to_read);
    
    if (bytes_read == 0) {
        printf("[GUI] ERROR: Failed to load RGB data\n");
        return 0;
    }
    
    // Verify CRC32
    if (header->crc32 != 0) {
        uint32_t calculated_crc = crc32(0xFFFFFFFF, rgb_buffer, bytes_read) ^ 0xFFFFFFFF;
        if (calculated_crc != header->crc32) {
            printf("[GUI] WARNING: CRC32 mismatch!\n");
        }
    }
    
    printf("[GUI] Loaded %u bytes of RGB data (%ux%u, %u bpp)\n", 
           bytes_read, header->width, header->height, header->bits_per_pixel);
    
    return bytes_read;
}
