/**
 * @file png_converter.h
 * @brief PNG to RGB Converter Task for GUIKit
 * 
 * This is a heavy task (Task B) that:
 * 1. Loads PNG file from SD card
 * 2. Decodes PNG to RGB format
 * 3. Saves RGB data to SD card for parent task to use
 * 4. Returns control to parent via task_restore()
 * 
 * This task is designed to be loaded by the task switcher:
 *   Task A (GUI) -> task_switch_to("/kernel/png_converter.bin") -> Task B
 *   Task B runs, does conversion, user clicks Back -> task_restore() -> Task A
 * 
 * Communication:
 *   Input:  PNG file path set by Task A (via command line or config)
 *   Output: RGB data saved to /tmp/task_comm/converted.rgb
 *           Header saved to /tmp/task_comm/converted.hdr
 * 
 * Generated by Mistral Vibe
 * Date: 2026-08-16
 */

#ifndef PNG_CONVERTER_H
#define PNG_CONVERTER_H

#include <stdint.h>
#include <stdbool.h>

// ============================================================================
// RGB IMAGE HEADER (for communication with parent task)
// ============================================================================

/// @brief RGB image header structure for parent task communication
/// @note Must match the RgbImageHeader in task_switcher_example.h
typedef struct {
    uint16_t width;            ///< Image width in pixels
    uint16_t height;           ///< Image height in pixels
    uint8_t bits_per_pixel;    ///< Bits per pixel (24 for RGB888)
    uint32_t data_size;        ///< Size of RGB data in bytes
    uint32_t crc32;            ///< CRC32 checksum of RGB data
    uint8_t reserved[16];      ///< Reserved for future use
} PngRgbHeader;

// ============================================================================
// CONFIGURATION
// ============================================================================

/// @brief Default input PNG path
#define PNG_CONVERTER_DEFAULT_INPUT "/images/input.png"

/// @brief Default output RGB path
#define PNG_CONVERTER_DEFAULT_OUTPUT "/tmp/task_comm/converted.rgb"

/// @brief Default output header path
#define PNG_CONVERTER_DEFAULT_HEADER "/tmp/task_comm/converted.hdr"

/// @brief Max image dimensions
#define PNG_CONVERTER_MAX_WIDTH 1024
#define PNG_CONVERTER_MAX_HEIGHT 768

// ============================================================================
// ERROR CODES
// ============================================================================

/// @brief PNG converter error codes
typedef enum {
    PNG_ERR_NONE = 0,
    PNG_ERR_FILE_NOT_FOUND,
    PNG_ERR_INVALID_PNG,
    PNG_ERR_UNSUPPORTED_FORMAT,
    PNG_ERR_MEMORY_ERROR,
    PNG_ERR_SD_CARD_ERROR,
    PNG_ERR_TOO_LARGE
} PngConverterError;

// ============================================================================
// MAIN FUNCTIONS
// ============================================================================

/**
 * @brief Main entry point for PNG converter task
 * 
 * This function:
 * 1. Initializes task switcher
 * 2. Checks if launched from parent task
 * 3. Loads PNG file
 * 4. Converts to RGB
 * 5. Saves results
 * 6. Waits for back button or auto-return
 * 
 * @param png_path Path to input PNG file (NULL for default)
 * @return true on success
 */
bool png_converter_run(const char* png_path);

/**
 * @brief Decode PNG file to RGB
 * 
 * @param png_path Path to PNG file
 * @param header Pointer to header struct to fill
 * @param rgb_buffer Buffer to store RGB data (allocated by caller)
 * @param buffer_size Size of buffer
 * @return Pointer to RGB data, or NULL on error
 */
uint8_t* png_decode_to_rgb(const char* png_path, 
                           PngRgbHeader* header, 
                           uint8_t* rgb_buffer, 
                           uint32_t buffer_size);

/**
 * @brief Get last error
 * 
 * @return Last error code
 */
PngConverterError png_converter_get_error(void);

/**
 * @brief Get error message string
 * 
 * @param error Error code
 * @return Human-readable error message
 */
const char* png_converter_error_to_string(PngConverterError error);

// ============================================================================
// UTILITY FUNCTIONS
// ============================================================================

/**
 * @brief Check if PNG file is valid
 * 
 * @param path Path to PNG file
 * @return true if valid PNG
 */
bool png_is_valid_file(const char* path);

/**
 * @brief Get PNG file dimensions without full decode
 * 
 * @param path Path to PNG file
 * @param width Output: width in pixels
 * @param height Output: height in pixels
 * @return true on success
 */
bool png_get_dimensions(const char* path, uint16_t* width, uint16_t* height);

/**
 * @brief Save RGB data for parent task
 * 
 * @param header Image header
 * @param rgb_data RGB pixel data
 * @param rgb_size Size of RGB data
 * @return true on success
 */
bool png_save_results(const PngRgbHeader* header, 
                     const uint8_t* rgb_data, 
                     uint32_t rgb_size);

// ============================================================================
// STANDALONE TASK ENTRY POINT
// ============================================================================

/**
 * @brief Standalone entry point when compiled as separate kernel
 * 
 * This is the main() equivalent for the PNG converter task.
 * It initializes everything and runs the converter.
 */
void png_converter_task_main(void);

#endif // PNG_CONVERTER_H
