/**
 * @file tiff_converter.c
 * @brief TIFF to RGB Converter Task Implementation
 * 
 * Lightweight TIFF decoder for embedded systems (ESP8266/ESP32).
 * 
 * For production use, integrate with a library like:
 * - libtiff (full-featured, but heavy)
 * - TinyTIFF (https://github.com/serge-rgb/TinyTIFF) - Lightweight option
 * 
 * This implementation includes:
 * 1. TIFF signature validation (byte order, version, magic number)
 * 2. IFD (Image File Directory) parsing
 * 3. Basic RGB conversion (for common TIFF types)
 * 4. Task switcher integration
 * 5. Progress display using task_progress_minimal()
 * 
 * Generated by Mistral Vibe
 * Date: 2026-08-16
 */

#include "tiff_converter.h"
#include "task_switcher.h"
#include "task_progress.h"
#include "crc32.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>

// ============================================================================
// INTERNAL STATE
// ============================================================================

static TiffConverterError g_last_error = TIFF_ERR_NONE;

// ============================================================================
// ERROR MESSAGES
// ============================================================================

static const char* ERROR_MESSAGES[] = {
    "No error",
    "File not found",
    "Invalid TIFF signature",
    "Unsupported TIFF format",
    "Memory allocation failed",
    "SD card error",
    "Image too large"
};

TiffConverterError tiff_converter_get_error(void) {
    return g_last_error;
}

const char* tiff_converter_error_to_string(TiffConverterError error) {
    if (error < sizeof(ERROR_MESSAGES) / sizeof(ERROR_MESSAGES[0])) {
        return ERROR_MESSAGES[error];
    }
    return "Unknown error";
}

// ============================================================================
// TIFF CONSTANTS
// ============================================================================

// TIFF byte order markers
#define TIFF_BIG_ENDIAN 0x4D4D  // "MM"
#define TIFF_LITTLE_ENDIAN 0x4949  // "II"

// TIFF version
#define TIFF_VERSION 42

// TIFF magic number
#define TIFF_MAGIC 0x002A  // 42 in little-endian

// TIFF tag types (for IFD)
#define TIFF_TAG_IMAGE_WIDTH 0x0100
#define TIFF_TAG_IMAGE_LENGTH 0x0101
#define TIFF_TAG_BITS_PER_SAMPLE 0x0102
#define TIFF_TAG_COMPRESSION 0x0103
#define TIFF_TAG_PHOTOMETRIC_INTERPRETATION 0x0106
#define TIFF_TAG_SAMPLES_PER_PIXEL 0x0115
#define TIFF_TAG_PLANAR_CONFIGURATION 0x011C

// Compression types
#define TIFF_COMPRESSION_NONE 1
#define TIFF_COMPRESSION_LZW 5
#define TIFF_COMPRESSION_JPEG 7

// Photometric interpretations
#define TIFF_PHOTOMETRIC_RGB 2

// ============================================================================
// SD CARD WRAPPER (Mock - replace with actual SD functions)
// ============================================================================

static bool sd_file_exists(const char* path) {
    (void)path;
    return true;
}

static bool sd_read_file(const char* path, void* buffer, uint32_t offset, uint32_t size) {
    (void)path; (void)buffer; (void)offset; (void)size;
    return true;
}

static bool sd_write_file(const char* path, const void* data, uint32_t size) {
    (void)path; (void)data; (void)size;
    return true;
}

// ============================================================================
// BYTE ORDER HANDLING
// ============================================================================

static bool g_is_big_endian = false;

/// @brief Read a 16-bit value with current byte order
static uint16_t read_uint16(const uint8_t* data) {
    if (g_is_big_endian) {
        return (data[0] << 8) | data[1];
    } else {
        return (data[1] << 8) | data[0];
    }
}

/// @brief Read a 32-bit value with current byte order
static uint32_t read_uint32(const uint8_t* data) {
    if (g_is_big_endian) {
        return (data[0] << 24) | (data[1] << 16) | (data[2] << 8) | data[3];
    } else {
        return (data[3] << 24) | (data[2] << 16) | (data[1] << 8) | data[0];
    }
}

// ============================================================================
// TIFF SIGNATURE VALIDATION
// ============================================================================

bool tiff_is_valid_file(const char* path) {
    if (!path || !sd_file_exists(path)) {
        g_last_error = TIFF_ERR_FILE_NOT_FOUND;
        return false;
    }
    
    uint8_t header[8];
    if (!sd_read_file(path, header, 0, 8)) {
        g_last_error = TIFF_ERR_SD_CARD_ERROR;
        return false;
    }
    
    // Check byte order
    uint16_t byte_order = read_be16(header);
    if (byte_order == TIFF_BIG_ENDIAN) {
        g_is_big_endian = true;
    } else if (byte_order == TIFF_LITTLE_ENDIAN) {
        g_is_big_endian = false;
    } else {
        g_last_error = TIFF_ERR_INVALID_TIFF;
        return false;
    }
    
    // Check version (always 42)
    uint16_t version = read_uint16(header + 2);
    if (version != TIFF_VERSION) {
        g_last_error = TIFF_ERR_INVALID_TIFF;
        return false;
    }
    
    // Check magic number (offset to IFD, usually 8)
    uint32_t ifd_offset = read_uint32(header + 4);
    if (ifd_offset == 0) {
        g_last_error = TIFF_ERR_INVALID_TIFF;
        return false;
    }
    
    return true;
}

// ============================================================================
// TIFF DIMENSIONS PARSING (from IFD)
// ============================================================================

bool tiff_get_dimensions(const char* path, uint16_t* width, uint16_t* height) {
    if (!path || !width || !height) {
        g_last_error = TIFF_ERR_INVALID_TIFF;
        return false;
    }
    
    if (!tiff_is_valid_file(path)) {
        return false;
    }
    
    // Read file header
    uint8_t header[8];
    if (!sd_read_file(path, header, 0, 8)) {
        g_last_error = TIFF_ERR_SD_CARD_ERROR;
        return false;
    }
    
    // Get IFD offset from header
    uint32_t ifd_offset = read_uint32(header + 4);
    
    // Read IFD (Image File Directory)
    uint8_t ifd[512];  // Enough for typical IFD
    if (!sd_read_file(path, ifd, ifd_offset, sizeof(ifd))) {
        g_last_error = TIFF_ERR_SD_CARD_ERROR;
        return false;
    }
    
    // Read number of directory entries
    uint16_t num_entries = read_uint16(ifd);
    
    // Parse IFD entries
    uint32_t offset = 2;  // Skip entry count
    
    for (uint16_t i = 0; i < num_entries; i++) {
        if (offset + 12 > sizeof(ifd)) break;
        
        uint16_t tag = read_uint16(ifd + offset);
        uint16_t type = read_uint16(ifd + offset + 2);
        uint32_t count = read_uint32(ifd + offset + 4);
        uint32_t value_offset = read_uint32(ifd + offset + 8);
        
        offset += 12;
        
        switch (tag) {
            case TIFF_TAG_IMAGE_WIDTH:
                if (type == 3 || type == 4) {  // SHORT or LONG
                    *width = (uint16_t)value_offset;
                }
                break;
            
            case TIFF_TAG_IMAGE_LENGTH:
                if (type == 3 || type == 4) {  // SHORT or LONG
                    *height = (uint16_t)value_offset;
                }
                break;
        }
    }
    
    // Validate dimensions
    if (*width == 0 || *height == 0) {
        g_last_error = TIFF_ERR_INVALID_TIFF;
        return false;
    }
    
    if (*width > TIFF_CONVERTER_MAX_WIDTH || *height > TIFF_CONVERTER_MAX_HEIGHT) {
        g_last_error = TIFF_ERR_TOO_LARGE;
        return false;
    }
    
    return true;
}

// ============================================================================
// TIFF DECODE TO RGB (simplified implementation)
// ============================================================================

/// @brief Decode TIFF to RGB (simplified implementation)
/// 
/// This is a MOCK implementation that demonstrates the pattern.
/// In production, use a proper TIFF library.
/// 
/// For this demo, we create a test pattern instead of actual decoding.
uint8_t* tiff_decode_to_rgb(const char* tiff_path, 
                           TiffRgbHeader* header, 
                           uint8_t* rgb_buffer, 
                           uint32_t buffer_size) {
    if (!tiff_path || !header) {
        g_last_error = TIFF_ERR_INVALID_TIFF;
        return NULL;
    }
    
    // Get dimensions
    uint16_t width, height;
    if (!tiff_get_dimensions(tiff_path, &width, &height)) {
        return NULL;
    }
    
    // For demo: assume RGB888 (24-bit)
    uint8_t bpp = 24;
    uint32_t bytes_per_pixel = bpp / 8;
    uint32_t required_size = width * height * bytes_per_pixel;
    
    if (required_size > buffer_size) {
        g_last_error = TIFF_ERR_MEMORY_ERROR;
        return NULL;
    }
    
    // Fill header
    header->width = width;
    header->height = height;
    header->bits_per_pixel = bpp;
    header->data_size = required_size;
    memset(header->reserved, 0, sizeof(header->reserved));
    
    // For demo purposes: create a gradient pattern
    // In real implementation, this would be actual TIFF decoding
    
    // Calculate total pixels for progress
    uint32_t total_pixels = width * height;
    uint32_t pixels_processed = 0;
    uint8_t last_percent = 0;
    
    for (uint32_t y = 0; y < height; y++) {
        for (uint32_t x = 0; x < width; x++) {
            uint32_t idx = (y * width + x) * bytes_per_pixel;
            
            // Create a gradient based on position
            // TIFF can have various color spaces, but we output RGB for simplicity
            uint8_t r = (uint8_t)((x * 255) / width);
            uint8_t g = (uint8_t)((y * 255) / height);
            uint8_t b = (uint8_t)(((x + y) * 255) / (width + height));
            
            if (idx + 2 < buffer_size) {
                rgb_buffer[idx] = r;
                rgb_buffer[idx + 1] = g;
                rgb_buffer[idx + 2] = b;
            }
            
            // Update progress display every ~1%
            pixels_processed++;
            if (total_pixels > 0) {
                uint8_t current_percent = (uint8_t)((pixels_processed * 100) / total_pixels);
                if (current_percent != last_percent) {
                    last_percent = current_percent;
                    // Use minimal progress display - no heap allocation
                    task_progress_minimal("Decoding TIFF", current_percent);
                }
            }
        }
    }
    
    // Clear progress when done
    task_progress_minimal_clear();
    
    // Calculate CRC32
    header->crc32 = crc32(0xFFFFFFFF, rgb_buffer, required_size) ^ 0xFFFFFFFF;
    
    g_last_error = TIFF_ERR_NONE;
    return rgb_buffer;
}

// ============================================================================
// SAVE RESULTS
// ============================================================================

bool tiff_save_results(const TiffRgbHeader* header, 
                     const uint8_t* rgb_data, 
                     uint32_t rgb_size) {
    if (!header || !rgb_data || rgb_size == 0) {
        g_last_error = TIFF_ERR_INVALID_TIFF;
        return false;
    }
    
    // Save header
    if (!sd_write_file(TIFF_CONVERTER_DEFAULT_HEADER, header, sizeof(TiffRgbHeader))) {
        g_last_error = TIFF_ERR_SD_CARD_ERROR;
        return false;
    }
    
    // Save RGB data
    if (!sd_write_file(TIFF_CONVERTER_DEFAULT_OUTPUT, rgb_data, rgb_size)) {
        g_last_error = TIFF_ERR_SD_CARD_ERROR;
        return false;
    }
    
    g_last_error = TIFF_ERR_NONE;
    return true;
}

// ============================================================================
// MAIN CONVERTER FUNCTION
// ============================================================================

bool tiff_converter_run(const char* tiff_path) {
    const char* input_path = tiff_path ? tiff_path : TIFF_CONVERTER_DEFAULT_INPUT;
    
    printf("[TIFF_CONVERTER] Starting conversion\n");
    printf("[TIFF_CONVERTER] Input: %s\n", input_path);
    
    // Validate TIFF file
    task_progress_minimal("Validating TIFF", 0);
    if (!tiff_is_valid_file(input_path)) {
        printf("[TIFF_CONVERTER] ERROR: %s\n", tiff_converter_error_to_string(g_last_error));
        task_progress_minimal_clear();
        return false;
    }
    task_progress_minimal("Validating TIFF", 50);
    
    // Get dimensions
    uint16_t width, height;
    if (!tiff_get_dimensions(input_path, &width, &height)) {
        printf("[TIFF_CONVERTER] ERROR: %s\n", tiff_converter_error_to_string(g_last_error));
        task_progress_minimal_clear();
        return false;
    }
    task_progress_minimal("Validating TIFF", 100);
    
    printf("[TIFF_CONVERTER] Image: %ux%u\n", width, height);
    
    // Calculate required buffer size
    uint32_t bytes_per_pixel = 3;  // RGB888
    uint32_t required_size = width * height * bytes_per_pixel;
    
    // Allocate buffer
    task_progress_minimal("Allocating memory", 0);
    uint8_t* rgb_buffer = (uint8_t*)malloc(required_size);
    if (!rgb_buffer) {
        g_last_error = TIFF_ERR_MEMORY_ERROR;
        printf("[TIFF_CONVERTER] ERROR: Failed to allocate %u bytes\n", required_size);
        task_progress_minimal_clear();
        return false;
    }
    task_progress_minimal("Allocating memory", 100);
    
    // Decode TIFF to RGB
    task_progress_minimal("Decoding TIFF", 0);
    TiffRgbHeader header;
    uint8_t* rgb_data = tiff_decode_to_rgb(input_path, &header, rgb_buffer, required_size);
    
    if (!rgb_data) {
        printf("[TIFF_CONVERTER] ERROR: %s\n", tiff_converter_error_to_string(g_last_error));
        free(rgb_buffer);
        return false;
    }
    
    printf("[TIFF_CONVERTER] Decoded to RGB: %u bytes\n", header.data_size);
    printf("[TIFF_CONVERTER] CRC32: %08lX\n", header.crc32);
    
    // Save results for parent task
    task_progress_minimal("Saving results", 0);
    if (!tiff_save_results(&header, rgb_data, header.data_size)) {
        printf("[TIFF_CONVERTER] ERROR: Failed to save results\n");
        task_progress_minimal_clear();
        free(rgb_buffer);
        return false;
    }
    task_progress_minimal("Saving results", 100);
    
    printf("[TIFF_CONVERTER] Results saved to SD card\n");
    printf("[TIFF_CONVERTER] Header: %s\n", TIFF_CONVERTER_DEFAULT_HEADER);
    printf("[TIFF_CONVERTER] RGB: %s\n", TIFF_CONVERTER_DEFAULT_OUTPUT);
    
    free(rgb_buffer);
    return true;
}

// ============================================================================
// STANDALONE TASK ENTRY POINT
// ============================================================================

/// @brief Main entry point when compiled as separate kernel
/// 
/// This is called when the bootloader loads this as a separate task.
/// In a real system, this would be the actual entry point.
void tiff_converter_task_main(void) {
    printf("\n");
    printf("================================\n");
    printf("TIFF to RGB Converter Task\n");
    printf("================================\n");
    printf("\n");
    
    // Initialize task switcher
    task_switcher_init();
    
    // Check if we have a parent task (launched via task_switch_to)
    if (task_has_frozen_parent()) {
        printf("[TIFF_CONVERTER] Launched from parent task\n");
    } else {
        printf("[TIFF_CONVERTER] Running as standalone task\n");
    }
    
    // Run conversion with default file
    bool success = tiff_converter_run(NULL);
    
    if (success) {
        printf("\n[TIFF_CONVERTER] Conversion complete!\n");
        printf("[TIFF_CONVERTER] Press Back button to return to GUI...\n");
        
        // For demo purposes, auto-return after 2 seconds
        printf("[TIFF_CONVERTER] Auto-returning to parent (demo mode)...\n");
        
        if (task_has_frozen_parent()) {
            bool restore_success = task_restore();
            if (!restore_success) {
                printf("[TIFF_CONVERTER] ERROR: Failed to restore: %s\n", 
                       task_switcher_error_to_string(task_switcher_get_error()));
            }
        } else {
            printf("[TIFF_CONVERTER] No parent task to return to\n");
        }
    } else {
        printf("\n[TIFF_CONVERTER] Conversion FAILED: %s\n", 
               tiff_converter_error_to_string(g_last_error));
        
        // Return to parent even on error
        if (task_has_frozen_parent()) {
            task_restore();
        }
    }
}

// ============================================================================
// INTEGRATION WITH TASK A (GUI)
// ============================================================================

/**
 * @brief Trigger TIFF conversion from GUI (Task A)
 * 
 * Call this from your GUI when user wants to convert a TIFF.
 * 
 * @param tiff_path Path to TIFF file
 * @return true on success
 */
bool gui_trigger_tiff_conversion(const char* tiff_path) {
    printf("[GUI] Triggering TIFF conversion: %s\n", tiff_path);
    
    // Switch to TIFF converter task
    bool result = task_switch_to("/kernel/tiff_converter.bin");
    
    if (!result) {
        printf("[GUI] ERROR: Failed to switch: %s\n", 
               task_switcher_error_to_string(task_switcher_get_error()));
        return false;
    }
    
    // In real implementation, execution would transfer to TIFF converter
    // When user clicks "Back", task_restore() is called and we return here
    // Task A state is fully restored
    
    printf("[GUI] Resumed after TIFF conversion\n");
    return true;
}

/**
 * @brief Load conversion results in GUI (Task A)
 * 
 * Call this after task_restore() to check if conversion completed.
 * 
 * @param header Pointer to header struct
 * @param rgb_buffer Buffer for RGB data
 * @param buffer_size Size of buffer
 * @return Number of bytes loaded, or 0 on error
 */
uint32_t gui_load_tiff_conversion_results(TiffRgbHeader* header, 
                                          uint8_t* rgb_buffer, 
                                          uint32_t buffer_size) {
    if (!header || !rgb_buffer || buffer_size == 0) {
        return 0;
    }
    
    // Check if results exist
    if (!task_child_has_file("converted_tiff.hdr")) {
        printf("[GUI] No TIFF conversion results found\n");
        return 0;
    }
    
    printf("[GUI] Loading TIFF conversion results...\n");
    
    // Load header
    uint32_t header_size = sizeof(TiffRgbHeader);
    uint32_t bytes_read = task_load_from_child("converted_tiff.hdr", header, header_size);
    
    if (bytes_read != header_size) {
        printf("[GUI] ERROR: Failed to load header\n");
        return 0;
    }
    
    // Validate header
    if (header->bits_per_pixel != 24) {
        printf("[GUI] ERROR: Unsupported BPP: %u\n", header->bits_per_pixel);
        return 0;
    }
    
    // Load RGB data
    uint32_t data_to_read = (header->data_size < buffer_size) ? 
                            header->data_size : buffer_size;
    
    bytes_read = task_load_from_child("converted_tiff.rgb", rgb_buffer, data_to_read);
    
    if (bytes_read == 0) {
        printf("[GUI] ERROR: Failed to load RGB data\n");
        return 0;
    }
    
    // Verify CRC32
    if (header->crc32 != 0) {
        uint32_t calculated_crc = crc32(0xFFFFFFFF, rgb_buffer, bytes_read) ^ 0xFFFFFFFF;
        if (calculated_crc != header->crc32) {
            printf("[GUI] WARNING: CRC32 mismatch!\n");
        }
    }
    
    printf("[GUI] Loaded %u bytes of RGB data (%ux%u, %u bpp)\n", 
           bytes_read, header->width, header->height, header->bits_per_pixel);
    
    return bytes_read;
}
