/**
 * @file tiff_converter.h
 * @brief TIFF to RGB Converter Task for GUIKit
 * 
 * This is a heavy task (Task B) that:
 * 1. Loads TIFF file from SD card
 * 2. Decodes TIFF to RGB format
 * 3. Saves RGB data to SD card for parent task to use
 * 4. Returns control to parent via task_restore()
 * 
 * This task is designed to be loaded by the task switcher:
 *   Task A (GUI) -> task_switch_to("/kernel/tiff_converter.bin") -> Task B
 *   Task B runs, does conversion, user clicks Back -> task_restore() -> Task A
 * 
 * Communication:
 *   Input:  TIFF file path set by Task A (via command line or config)
 *   Output: RGB data saved to /tmp/task_comm/converted_tiff.rgb
 *           Header saved to /tmp/task_comm/converted_tiff.hdr
 * 
 * Generated by Mistral Vibe
 * Date: 2026-08-16
 */

#ifndef TIFF_CONVERTER_H
#define TIFF_CONVERTER_H

#include <stdint.h>
#include <stdbool.h>

// ============================================================================
// RGB IMAGE HEADER (for communication with parent task)
// ============================================================================

/// @brief RGB image header structure for parent task communication
/// @note Must match the PngRgbHeader in png_converter.h for consistency
typedef struct {
    uint16_t width;            ///< Image width in pixels
    uint16_t height;           ///< Image height in pixels
    uint8_t bits_per_pixel;    ///< Bits per pixel (24 for RGB888)
    uint32_t data_size;        ///< Size of RGB data in bytes
    uint32_t crc32;            ///< CRC32 checksum of RGB data
    uint8_t reserved[16];      ///< Reserved for future use
} TiffRgbHeader;

// ============================================================================
// CONFIGURATION
// ============================================================================

/// @brief Default input TIFF path
#define TIFF_CONVERTER_DEFAULT_INPUT "/images/input.tif"

/// @brief Default output RGB path
#define TIFF_CONVERTER_DEFAULT_OUTPUT "/tmp/task_comm/converted_tiff.rgb"

/// @brief Default output header path
#define TIFF_CONVERTER_DEFAULT_HEADER "/tmp/task_comm/converted_tiff.hdr"

/// @brief Max image dimensions
#define TIFF_CONVERTER_MAX_WIDTH 1024
#define TIFF_CONVERTER_MAX_HEIGHT 768

// ============================================================================
// ERROR CODES
// ============================================================================

/// @brief TIFF converter error codes
typedef enum {
    TIFF_ERR_NONE = 0,
    TIFF_ERR_FILE_NOT_FOUND,
    TIFF_ERR_INVALID_TIFF,
    TIFF_ERR_UNSUPPORTED_FORMAT,
    TIFF_ERR_MEMORY_ERROR,
    TIFF_ERR_SD_CARD_ERROR,
    TIFF_ERR_TOO_LARGE
} TiffConverterError;

// ============================================================================
// MAIN FUNCTIONS
// ============================================================================

/**
 * @brief Main entry point for TIFF converter task
 * 
 * This function:
 * 1. Initializes task switcher
 * 2. Checks if launched from parent task
 * 3. Loads TIFF file
 * 4. Converts to RGB
 * 5. Saves results
 * 6. Waits for back button or auto-return
 * 
 * @param tiff_path Path to input TIFF file (NULL for default)
 * @return true on success
 */
bool tiff_converter_run(const char* tiff_path);

/**
 * @brief Decode TIFF file to RGB
 * 
 * @param tiff_path Path to TIFF file
 * @param header Pointer to header struct to fill
 * @param rgb_buffer Buffer to store RGB data (allocated by caller)
 * @param buffer_size Size of buffer
 * @return Pointer to RGB data, or NULL on error
 */
uint8_t* tiff_decode_to_rgb(const char* tiff_path, 
                           TiffRgbHeader* header, 
                           uint8_t* rgb_buffer, 
                           uint32_t buffer_size);

/**
 * @brief Get last error
 * 
 * @return Last error code
 */
TiffConverterError tiff_converter_get_error(void);

/**
 * @brief Get error message string
 * 
 * @param error Error code
 * @return Human-readable error message
 */
const char* tiff_converter_error_to_string(TiffConverterError error);

// ============================================================================
// UTILITY FUNCTIONS
// ============================================================================

/**
 * @brief Check if TIFF file is valid
 * 
 * @param path Path to TIFF file
 * @return true if valid TIFF
 */
bool tiff_is_valid_file(const char* path);

/**
 * @brief Get TIFF file dimensions without full decode
 * 
 * @param path Path to TIFF file
 * @param width Output: width in pixels
 * @param height Output: height in pixels
 * @return true on success
 */
bool tiff_get_dimensions(const char* path, uint16_t* width, uint16_t* height);

/**
 * @brief Save RGB data for parent task
 * 
 * @param header Image header
 * @param rgb_data RGB pixel data
 * @param rgb_size Size of RGB data
 * @return true on success
 */
bool tiff_save_results(const TiffRgbHeader* header, 
                     const uint8_t* rgb_data, 
                     uint32_t rgb_size);

// ============================================================================
// STANDALONE TASK ENTRY POINT
// ============================================================================

/**
 * @brief Standalone entry point when compiled as separate kernel
 * 
 * This is the main() equivalent for the TIFF converter task.
 * It initializes everything and runs the converter.
 */
void tiff_converter_task_main(void);

#endif // TIFF_CONVERTER_H
