/**
 * @file mdns_service.c
 * @brief mDNS Service Discovery Implementation for ESP8266/ESP32
 *
 * Implements Bonjour/Zeroconf service advertisement using ESP8266mDNS library.
 * This module MUST be included in Kernel.bin (SD card) as it requires network connectivity.
 *
 * Features:
 * - Device discovery via [hostname].local
 * - Service advertisement (HTTP, WebDAV, GUIKit)
 * - TXT records for service metadata
 * - Custom service support
 * - Hostname validation and generation
 *
 * Generated by Mistral Vibe.
 * Date: 2026-08-16
 */

#include "mdns_service.h"
#include <string.h>
#include <stdlib.h>
#include <stdio.h>

// ============================================================================
// PLATFORM-SPECIFIC INCLUDES
// ============================================================================

#if defined(ESP8266)
    #include <ESP8266mDNS.h>
    #include <ESP8266WiFi.h>
#elif defined(ESP32)
    #include <ESPmDNS.h>
    #include <WiFi.h>
#else
    #error "mDNS service requires ESP8266 or ESP32 platform"
#endif

// ============================================================================
// INTERNAL STATE
// ============================================================================

static bool g_mdns_initialized = false;
static bool g_mdns_started = false;
static char g_hostname[MDNS_MAX_HOSTNAME + 1] = MDNS_DEFAULT_HOSTNAME;
static char g_fqdn[MDNS_MAX_FQDN] = {0};
static mDNSConfig g_config;

// Custom services tracking
static mDNSServiceInfo g_custom_services[MDNS_MAX_CUSTOM_SERVICES];
static uint8_t g_custom_service_count = 0;

// ============================================================================
// ERROR CODES
// ============================================================================

/// @brief mDNS error codes
typedef enum {
    MDNS_ERROR_NONE = 0,           ///< No error
    MDNS_ERROR_INIT_FAILED,       ///< Failed to initialize mDNS
    MDNS_ERROR_ALREADY_STARTED,   ///< mDNS already running
    MDNS_ERROR_NOT_STARTED,       ///< mDNS not running
    MDNS_ERROR_INVALID_HOSTNAME, ///< Invalid hostname
    MDNS_ERROR_SERVICE_EXISTS,    ///< Service already exists
    MDNS_ERROR_TOO_MANY_SERVICES, ///< Maximum services reached
    MDNS_ERROR_NO_WIFI,           ///< WiFi not connected
} mDNSErorCode;

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/// @brief Check if hostname contains only valid characters
/// @param hostname Hostname to check
/// @return true if valid
static bool is_valid_hostname_chars(const char* hostname) {
    if (!hostname) return false;
    
    for (int i = 0; hostname[i] != '\0'; i++) {
        char c = hostname[i];
        // Valid: a-z, A-Z, 0-9, hyphen
        if (!((c >= 'a' && c <= 'z') ||
              (c >= 'A' && c <= 'Z') ||
              (c >= '0' && c <= '9') ||
              c == '-')) {
            return false;
        }
    }
    return true;
}

// ============================================================================
// INITIALIZATION
// ============================================================================

bool mdns_init(const mDNSConfig* config) {
    // Check WiFi connection
    #if defined(ESP8266)
        if (WiFi.status() != WL_CONNECTED) {
            return false;
        }
    #elif defined(ESP32)
        if (WiFi.status() != WL_CONNECTED) {
            return false;
        }
    #endif

    if (g_mdns_started) {
        return true;  // Already running
    }

    // Apply configuration
    if (config) {
        g_config = *config;
    } else {
        g_config = (mDNSConfig) {
            .hostname = MDNS_DEFAULT_HOSTNAME,
            .enable_http = true,
            .enable_webdav = true,
            .enable_guikit = true,
            .http_port = 80,
            .webdav_port = 80,
            .guikit_port = 8080,
            .model = "ESP8266 NodeMCU",
            .manufacturer = "Genose.org",
            .serial_number = "GUIKit_Device",
            .version = "1.0.0"
        };
    }

    // Validate and set hostname
    if (!g_config.hostname || !is_valid_hostname_chars(g_config.hostname)) {
        // Use default
        strncpy(g_hostname, MDNS_DEFAULT_HOSTNAME, sizeof(g_hostname) - 1);
        g_hostname[sizeof(g_hostname) - 1] = '\0';
    } else {
        strncpy(g_hostname, g_config.hostname, sizeof(g_hostname) - 1);
        g_hostname[sizeof(g_hostname) - 1] = '\0';
    }

    // Build FQDN
    snprintf(g_fqdn, sizeof(g_fqdn), "%s.local", g_hostname);

    // Start mDNS
    if (!MDNS.begin(g_hostname)) {
        return false;
    }

    g_mdns_started = true;
    g_mdns_initialized = true;

    // Advertise HTTP service
    if (g_config.enable_http) {
        MDNS.addService("http", "tcp", g_config.http_port);
        MDNS.addServiceTxt("http", "tcp", "model", g_config.model);
        MDNS.addServiceTxt("http", "tcp", "manufacturer", g_config.manufacturer);
        MDNS.addServiceTxt("http", "tcp", "path", "/");
    }

    // Advertise WebDAV service
    if (g_config.enable_webdav) {
        MDNS.addService("webdav", "tcp", g_config.webdav_port);
        MDNS.addServiceTxt("webdav", "tcp", "model", g_config.model);
        MDNS.addServiceTxt("webdav", "tcp", "manufacturer", g_config.manufacturer);
        MDNS.addServiceTxt("webdav", "tcp", "path", "/webdav");
    }

    // Advertise GUIKit service
    if (g_config.enable_guikit) {
        MDNS.addService("guikit", "tcp", g_config.guikit_port);
        MDNS.addServiceTxt("guikit", "tcp", "model", g_config.model);
        MDNS.addServiceTxt("guikit", "tcp", "manufacturer", g_config.manufacturer);
        MDNS.addServiceTxt("guikit", "tcp", "serial", g_config.serial_number);
        MDNS.addServiceTxt("guikit", "tcp", "version", g_config.version);
    }

    return true;
}

void mdns_shutdown(void) {
    if (g_mdns_started) {
        MDNS.end();
        g_mdns_started = false;
    }
    g_mdns_initialized = false;
    g_custom_service_count = 0;
}

bool mdns_is_running(void) {
    return g_mdns_started;
}

bool mdns_reinit(const mDNSConfig* config) {
    mdns_shutdown();
    return mdns_init(config);
}

// ============================================================================
// HOSTNAME MANAGEMENT
// ============================================================================

bool mdns_set_hostname(const char* hostname) {
    if (!hostname || !is_valid_hostname_chars(hostname)) {
        return false;
    }

    if (strlen(hostname) > MDNS_MAX_HOSTNAME) {
        return false;
    }

    strncpy(g_hostname, hostname, sizeof(g_hostname) - 1);
    g_hostname[sizeof(g_hostname) - 1] = '\0';

    // Rebuild FQDN
    snprintf(g_fqdn, sizeof(g_fqdn), "%s.local", g_hostname);

    // Restart mDNS with new hostname
    if (g_mdns_started) {
        mdns_reinit(&g_config);
    }

    return true;
}

const char* mdns_get_hostname(void) {
    return g_hostname;
}

const char* mdns_get_fqdn(void) {
    return g_fqdn;
}

// ============================================================================
// SERVICE MANAGEMENT
// ============================================================================

bool mdns_add_service(
    const char* instance_name,
    const char* service_type,
    uint16_t port,
    const char* path,
    const char* txt_key,
    const char* txt_value
) {
    if (!g_mdns_started || !instance_name || !service_type) {
        return false;
    }

    // Check if service already exists
    for (uint8_t i = 0; i < g_custom_service_count; i++) {
        if (strcmp(g_custom_services[i].name, instance_name) == 0 &&
            strcmp(g_custom_services[i].service_type, service_type) == 0) {
            return false;  // Service already exists
        }
    }

    // Check if we have space
    if (g_custom_service_count >= MDNS_MAX_CUSTOM_SERVICES) {
        return false;
    }

    // Store service info
    mDNSServiceInfo* service = &g_custom_services[g_custom_service_count++];
    strncpy(service->name, instance_name, sizeof(service->name) - 1);
    service->name[sizeof(service->name) - 1] = '\0';
    service->service_type = service_type;
    service->protocol = "tcp";
    service->port = port;
    if (path) {
        strncpy(service->path, path, sizeof(service->path) - 1);
        service->path[sizeof(service->path) - 1] = '\0';
    } else {
        service->path[0] = '\0';
    }

    // Add to mDNS
    bool success = MDNS.addService(instance_name, "tcp", port);
    
    if (success && txt_key && txt_value) {
        MDNS.addServiceTxt(instance_name, "tcp", txt_key, txt_value);
    }

    return success;
}

bool mdns_add_service_with_txt(
    const char* instance_name,
    const char* service_type,
    uint16_t port,
    const char* path,
    const char** txt_records
) {
    if (!g_mdns_started || !instance_name || !service_type) {
        return false;
    }

    // Check if service already exists
    for (uint8_t i = 0; i < g_custom_service_count; i++) {
        if (strcmp(g_custom_services[i].name, instance_name) == 0 &&
            strcmp(g_custom_services[i].service_type, service_type) == 0) {
            return false;
        }
    }

    if (g_custom_service_count >= MDNS_MAX_CUSTOM_SERVICES) {
        return false;
    }

    // Store service info
    mDNSServiceInfo* service = &g_custom_services[g_custom_service_count++];
    strncpy(service->name, instance_name, sizeof(service->name) - 1);
    service->name[sizeof(service->name) - 1] = '\0';
    service->service_type = service_type;
    service->protocol = "tcp";
    service->port = port;
    if (path) {
        strncpy(service->path, path, sizeof(service->path) - 1);
        service->path[sizeof(service->path) - 1] = '\0';
    } else {
        service->path[0] = '\0';
    }

    // Add service
    if (!MDNS.addService(instance_name, "tcp", port)) {
        g_custom_service_count--;
        return false;
    }

    // Add TXT records
    if (txt_records) {
        for (int i = 0; txt_records[i] != NULL; i += 2) {
            if (txt_records[i + 1] != NULL) {
                MDNS.addServiceTxt(instance_name, "tcp", txt_records[i], txt_records[i + 1]);
            }
        }
    }

    return true;
}

void mdns_remove_service(const char* instance_name, const char* service_type) {
    if (!g_mdns_started) return;

    // Find and remove from tracking
    for (uint8_t i = 0; i < g_custom_service_count; i++) {
        if (strcmp(g_custom_services[i].name, instance_name) == 0 &&
            strcmp(g_custom_services[i].service_type, service_type) == 0) {
            // Remove from array
            for (uint8_t j = i; j < g_custom_service_count - 1; j++) {
                g_custom_services[j] = g_custom_services[j + 1];
            }
            g_custom_service_count--;
            break;
        }
    }

    // Remove from mDNS
    MDNS.removeService(instance_name, "tcp");
}

void mdns_remove_all_services(void) {
    // Remove all custom services from mDNS
    for (uint8_t i = 0; i < g_custom_service_count; i++) {
        MDNS.removeService(g_custom_services[i].name, "tcp");
    }
    g_custom_service_count = 0;
}

bool mdns_get_service_info(uint8_t index, mDNSServiceInfo* info) {
    if (index >= g_custom_service_count) {
        return false;
    }
    *info = g_custom_services[index];
    return true;
}

// ============================================================================
// MAINTENANCE
// ============================================================================

void mdns_process(void) {
    if (g_mdns_started) {
        MDNS.update();
    }
}

int mdns_get_error(void) {
    if (!g_mdns_started) {
        return MDNS_ERROR_NOT_STARTED;
    }
    return MDNS_ERROR_NONE;
}

const char* mdns_error_to_string(int error_code) {
    switch (error_code) {
        case MDNS_ERROR_NONE: return "No error";
        case MDNS_ERROR_INIT_FAILED: return "Failed to initialize mDNS";
        case MDNS_ERROR_ALREADY_STARTED: return "mDNS already running";
        case MDNS_ERROR_NOT_STARTED: return "mDNS not running";
        case MDNS_ERROR_INVALID_HOSTNAME: return "Invalid hostname";
        case MDNS_ERROR_SERVICE_EXISTS: return "Service already exists";
        case MDNS_ERROR_TOO_MANY_SERVICES: return "Too many services";
        case MDNS_ERROR_NO_WIFI: return "WiFi not connected";
        default: return "Unknown error";
    }
}

// ============================================================================
// UTILITY FUNCTIONS
// ============================================================================

bool mdns_is_valid_hostname(const char* hostname) {
    if (!hostname) return false;
    
    size_t len = strlen(hostname);
    if (len == 0 || len > MDNS_MAX_HOSTNAME) {
        return false;
    }
    
    return is_valid_hostname_chars(hostname);
}

void mdns_generate_unique_hostname(const char* base_name, char* buffer) {
    if (!base_name || !buffer) {
        if (buffer) {
            strncpy(buffer, MDNS_DEFAULT_HOSTNAME, MDNS_MAX_HOSTNAME);
            buffer[MDNS_MAX_HOSTNAME] = '\0';
        }
        return;
    }

    // Use base name if valid
    if (mdns_is_valid_hostname(base_name) && strlen(base_name) <= MDNS_MAX_HOSTNAME) {
        strncpy(buffer, base_name, MDNS_MAX_HOSTNAME);
        buffer[MDNS_MAX_HOSTNAME] = '\0';
        return;
    }

    // Otherwise use default
    strncpy(buffer, MDNS_DEFAULT_HOSTNAME, MDNS_MAX_HOSTNAME);
    buffer[MDNS_MAX_HOSTNAME] = '\0';
}

// ============================================================================
// INTEGRATION WITH KERNEL
// ============================================================================

/// @brief Initialize mDNS as part of kernel startup
/// @param device_name Custom device name (NULL for default)
/// @return true on success
bool kernel_mdns_init(const char* device_name) {
    mDNSConfig config = MDNS_DEFAULT_CONFIG;
    
    if (device_name) {
        // Generate unique hostname based on device name
        char unique_name[MDNS_MAX_HOSTNAME + 1];
        mdns_generate_unique_hostname(device_name, unique_name);
        config.hostname = unique_name;
    }
    
    return mdns_init(&config);
}

/// @brief Get discovery URL for WebDAV
/// @return URL string (e.g., "http://esp8266.local/webdav")
void mdns_get_webdav_url(char* buffer, size_t buffer_size) {
    if (buffer && buffer_size > 0) {
        snprintf(buffer, buffer_size, "http://%s/webdav", mdns_get_fqdn());
    }
}

/// @brief Get discovery URL for GUIKit
/// @return URL string (e.g., "http://esp8266.local/gui")
void mdns_get_guikit_url(char* buffer, size_t buffer_size) {
    if (buffer && buffer_size > 0) {
        snprintf(buffer, buffer_size, "http://%s/gui", mdns_get_fqdn());
    }
}
