/**
 * @file mdns_service.h
 * @brief mDNS Service Discovery for ESP8266/ESP32
 *
 * Provides Bonjour/Zeroconf service advertisement for:
 * - HTTP/Web server
 * - WebDAV server
 * - Custom GUIKit services
 *
 * Allows clients to discover ESP8266 at http://[hostname].local
 * without requiring DNS server or /etc/hosts entries.
 *
 * Service Types:
 * - _http._tcp - HTTP/Web server (port 80)
 * - _webdav._tcp - WebDAV server (port 80)
 * - _guikit._tcp - GUIKit custom service (port 8080)
 *
 * Generated by Mistral Vibe.
 * Date: 2026-08-16
 */

#ifndef MDNS_SERVICE_H
#define MDNS_SERVICE_H

#include <stdint.h>
#include <stdbool.h>

// ============================================================================
// SERVICE TYPE DEFINITIONS
// ============================================================================

/// @brief Standard HTTP service type (RFC 6761)
#define MDNS_SERVICE_HTTP "_http._tcp"

/// @brief Standard WebDAV service type
#define MDNS_SERVICE_WEBDAV "_webdav._tcp"

/// @brief Custom GUIKit service type
#define MDNS_SERVICE_GUIKIT "_guikit._tcp"

/// @brief Default hostname for the device
#define MDNS_DEFAULT_HOSTNAME "esp8266"

/// @brief Maximum hostname length (RFC 1035: 63 chars)
#define MDNS_MAX_HOSTNAME 63

/// @brief Maximum FQDN length (hostname + .local)
#define MDNS_MAX_FQDN 128

// ============================================================================
// TXT RECORD KEYS
// ============================================================================

/// @brief TXT record key for device model
#define MDNS_TXT_MODEL "model"

/// @brief TXT record key for manufacturer
#define MDNS_TXT_MANUFACTURER "manufacturer"

/// @brief TXT record key for serial number
#define MDNS_TXT_SERIAL "serial"

/// @brief TXT record key for device name
#define MDNS_TXT_NAME "name"

/// @brief TXT record key for version
#define MDNS_TXT_VERSION "version"

/// @brief TXT record key for path
#define MDNS_TXT_PATH "path"

/// @brief TXT record key for description
#define MDNS_TXT_DESCRIPTION "description"

// ============================================================================
// CONFIGURATION
// ============================================================================

/// @brief Maximum number of custom services
#define MDNS_MAX_CUSTOM_SERVICES 8

/// @brief mDNS Configuration structure
typedef struct {
    const char* hostname;           ///< Device hostname (e.g., "esp8266" -> esp8266.local)
    bool enable_http;              ///< Advertise HTTP service
    bool enable_webdav;           ///< Advertise WebDAV service
    bool enable_guikit;            ///< Advertise GUIKit custom service
    uint16_t http_port;            ///< HTTP port (default: 80)
    uint16_t webdav_port;          ///< WebDAV port (default: 80)
    uint16_t guikit_port;          ///< GUIKit service port (default: 8080)
    const char* model;             ///< Device model (e.g., "ESP8266 NodeMCU")
    const char* manufacturer;      ///< Manufacturer (e.g., "Genose.org")
    const char* serial_number;     ///< Device serial/ID
    const char* version;           ///< Firmware version
} mDNSConfig;

/// @brief Service information structure
typedef struct {
    char name[64];                ///< Service instance name
    const char* service_type;      ///< Service type (e.g., "_http._tcp")
    const char* protocol;        ///< Protocol (e.g., "tcp")
    uint16_t port;                ///< Port number
    char path[64];                ///< Service path
} mDNSServiceInfo;

// ============================================================================
// DEFAULT CONFIGURATION
// ============================================================================

/// @brief Default mDNS configuration
#define MDNS_DEFAULT_CONFIG {\

    .hostname = MDNS_DEFAULT_HOSTNAME,\

    .enable_http = true,\

    .enable_webdav = true,\

    .enable_guikit = true,\

    .http_port = 80,\

    .webdav_port = 80,\

    .guikit_port = 8080,\

    .model = "ESP8266 NodeMCU",\

    .manufacturer = "Genose.org",\

    .serial_number = "GUIKit_Device",\

    .version = "1.0.0"\
}

// ============================================================================
// INITIALIZATION
// ============================================================================

/**
 * @brief Initialize mDNS service discovery
 *
 * Call this after WiFi connection is established.
 * Advertises the device on the local network as [hostname].local
 *
 * @param config Configuration (NULL for defaults)
 * @return true on success, false on failure
 */
bool mdns_init(const mDNSConfig* config);

/**
 * @brief Shutdown mDNS service
 *
 * Stops all service advertisements and releases resources.
 */
void mdns_shutdown(void);

/**
 * @brief Check if mDNS is running
 *
 * @return true if mDNS service is active
 */
bool mdns_is_running(void);

/**
 * @brief Reinitialize mDNS with new configuration
 *
 * @param config New configuration
 * @return true on success
 */
bool mdns_reinit(const mDNSConfig* config);

// ============================================================================
// HOSTNAME MANAGEMENT
// ============================================================================

/**
 * @brief Set the device hostname
 *
 * Updates the hostname and restarts mDNS service.
 *
 * @param hostname New hostname (max 63 chars, a-z, A-Z, 0-9, hyphen)
 * @return true on success
 */
bool mdns_set_hostname(const char* hostname);

/**
 * @brief Get current hostname
 *
 * @return Current hostname string
 */
const char* mdns_get_hostname(void);

/**
 * @brief Get Fully Qualified Domain Name (FQDN)
 *
 * Returns hostname.local
 *
 * @return FQDN string (e.g., "esp8266.local")
 */
const char* mdns_get_fqdn(void);

// ============================================================================
// SERVICE MANAGEMENT
// ============================================================================

/**
 * @brief Add a custom service to advertise
 *
 * @param instance_name Service instance name (unique on network)
 * @param service_type Service type (e.g., "_myapp._tcp")
 * @param port Port number
 * @param path Service path (optional, e.g., "/api")
 * @param txt_key TXT record key (NULL for none)
 * @param txt_value TXT record value (NULL for none)
 * @return true on success
 */
bool mdns_add_service(
    const char* instance_name,
    const char* service_type,
    uint16_t port,
    const char* path,
    const char* txt_key,
    const char* txt_value
);

/**
 * @brief Add a custom service with multiple TXT records
 *
 * @param instance_name Service instance name
 * @param service_type Service type
 * @param port Port number
 * @param path Service path
 * @param txt_records Array of key-value pairs (NULL-terminated)
 * @return true on success
 */
bool mdns_add_service_with_txt(
    const char* instance_name,
    const char* service_type,
    uint16_t port,
    const char* path,
    const char** txt_records  // Format: "key1", "value1", "key2", "value2", NULL
);

/**
 * @brief Remove a service
 *
 * @param instance_name Service instance name
 * @param service_type Service type
 */
void mdns_remove_service(const char* instance_name, const char* service_type);

/**
 * @brief Remove all custom services
 */
void mdns_remove_all_services(void);

/**
 * @brief Get information about a service
 *
 * @param index Service index (0 to MDNS_MAX_CUSTOM_SERVICES-1)
 * @param info Output service info structure
 * @return true if service exists
 */
bool mdns_get_service_info(uint8_t index, mDNSServiceInfo* info);

// ============================================================================
// MAINTENANCE
// ============================================================================

/**
 * @brief Process mDNS events
 *
 * Call this periodically in the main loop to handle mDNS requests.
 */
void mdns_process(void);

/**
 * @brief Check for mDNS errors
 *
 * @return Error code, 0 on success
 */
int mdns_get_error(void);

/**
 * @brief Get error message string
 *
 * @param error_code Error code from mdns_get_error()
 * @return Error message string
 */
const char* mdns_error_to_string(int error_code);

// ============================================================================
// UTILITY FUNCTIONS
// ============================================================================

/**
 * @brief Check if a hostname is valid for mDNS
 *
 * Valid: a-z, A-Z, 0-9, hyphen, max 63 chars
 *
 * @param hostname Hostname to validate
 * @return true if valid
 */
bool mdns_is_valid_hostname(const char* hostname);

/**
 * @brief Generate a unique hostname
 *
 * Combines base name with chip ID to ensure uniqueness.
 *
 * @param base_name Base hostname (e.g., "esp8266")
 * @param buffer Output buffer (must be at least MDNS_MAX_HOSTNAME+1 bytes)
 */
void mdns_generate_unique_hostname(const char* base_name, char* buffer);

#endif // MDNS_SERVICE_H
