/**
 * GUIKit External RAM GUI Loader
 * 
 * Loads GUI JSON files into external SRAM instead of internal RAM
 * Uses SPI SRAM (23LC1024) for storing GUI definitions and widget data
 * 
 * Generated by Mistral Vibe
 * Date: 2026-08-15
 */

#ifndef GUI_LOADER_EXTERNAL_RAM_H
#define GUI_LOADER_EXTERNAL_RAM_H

#include <stdint.h>
#include <stdbool.h>
#include "widget_pool.h"

// Forward declarations
class SPISRAM;
void* gui_loader_parse_json(const char* json);

// ============================================================================
// Configuration
// ============================================================================

// Address range for GUI storage in external SRAM
#define GUI_EXTERNAL_RAM_START_ADDR 0x000000  // Start at beginning of SRAM
#define GUI_EXTERNAL_RAM_MAX_SIZE (128 * 1024)  // Max GUI size in external RAM (128KB for 23LC1024)

// GUI JSON storage area
#define GUI_JSON_STORAGE_ADDR GUI_EXTERNAL_RAM_START_ADDR
#define GUI_JSON_MAX_SIZE (32 * 1024)  // Max JSON size (32KB)

// Widget data storage area (after JSON)
#define GUI_WIDGET_STORAGE_ADDR (GUI_JSON_STORAGE_ADDR + GUI_JSON_MAX_SIZE)
#define GUI_WIDGET_STORAGE_SIZE (GUI_EXTERNAL_RAM_MAX_SIZE - GUI_JSON_MAX_SIZE)

// ============================================================================
// External RAM GUI Loader Functions
// ============================================================================

/**
 * Initialize external RAM GUI loader
 * Must be called after SPISRAM initialization
 * 
 * @param sram Pointer to initialized SPISRAM instance
 * @return true on success
 */
bool gui_external_ram_init(SPISRAM* sram);

/**
 * Load GUI JSON from SD card into external RAM
 * 
 * @param filepath Path to GUI JSON file on SD card
 * @param sram Pointer to SPISRAM instance
 * @return true on success, false on failure
 */
bool gui_external_ram_load_from_sd(const char* filepath, SPISRAM* sram);

/**
 * Load GUI JSON from WebDAV into external RAM
 * 
 * @param filename GUI filename on WebDAV
 * @param sram Pointer to SPISRAM instance
 * @return true on success, false on failure
 */
bool gui_external_ram_load_from_webdav(const char* filename, SPISRAM* sram);

/**
 * Load GUI JSON string into external RAM
 * 
 * @param json GUI JSON string
 * @param sram Pointer to SPISRAM instance
 * @return true on success, false on failure
 */
bool gui_external_ram_load_from_string(const char* json, SPISRAM* sram);

/**
 * Parse GUI from external RAM
 * 
 * @param sram Pointer to SPISRAM instance
 * @param json_addr Address in SRAM where JSON is stored (default: GUI_JSON_STORAGE_ADDR)
 * @return Pointer to parsed GUI structure, or NULL on error
 * @note Caller must NOT free the returned pointer (data is in external RAM)
 */
void* gui_external_ram_parse(SPISRAM* sram, uint32_t json_addr = GUI_JSON_STORAGE_ADDR);

/**
 * Get JSON from external RAM
 * 
 * @param sram Pointer to SPISRAM instance
 * @param buffer Buffer to copy JSON into
 * @param buffer_size Size of buffer
 * @param json_addr Address in SRAM where JSON is stored
 * @return Number of bytes copied, or negative on error
 */
int gui_external_ram_get_json(SPISRAM* sram, char* buffer, int buffer_size, uint32_t json_addr = GUI_JSON_STORAGE_ADDR);

/**
 * Check if GUI is loaded in external RAM
 * 
 * @param sram Pointer to SPISRAM instance
 * @return true if GUI data exists at GUI_JSON_STORAGE_ADDR
 */
bool gui_external_ram_has_gui(SPISRAM* sram);

/**
 * Get size of GUI JSON in external RAM
 * 
 * @param sram Pointer to SPISRAM instance
 * @return Size in bytes, or 0 if no GUI loaded
 */
uint32_t gui_external_ram_get_gui_size(SPISRAM* sram);

/**
 * Clear GUI from external RAM
 * 
 * @param sram Pointer to SPISRAM instance
 */
void gui_external_ram_clear(SPISRAM* sram);

// ============================================================================
// External RAM Widget Allocation
// ============================================================================

/**
 * Allocate widget from external RAM pool
 * 
 * @param type Widget type
 * @param sram Pointer to SPISRAM instance
 * @return Pointer to widget in external RAM, or NULL on failure
 * @note Widgets allocated this way are stored in external RAM
 */
Widget* gui_external_ram_widget_alloc(WIDGET_TYPE type, SPISRAM* sram);

/**
 * Initialize external RAM widget pools
 * Creates widget pools in external SRAM
 * 
 * @param sram Pointer to SPISRAM instance
 * @return true on success
 */
bool gui_external_ram_pools_init(SPISRAM* sram);

// ============================================================================
// Configuration Getters
// ============================================================================

/**
 * Get start address for GUI storage
 */
static inline uint32_t gui_external_ram_get_start_addr() {
    return GUI_EXTERNAL_RAM_START_ADDR;
}

/**
 * Get max GUI size
 */
static inline uint32_t gui_external_ram_get_max_size() {
    return GUI_EXTERNAL_RAM_MAX_SIZE;
}

/**
 * Get JSON storage address
 */
static inline uint32_t gui_external_ram_get_json_addr() {
    return GUI_JSON_STORAGE_ADDR;
}

/**
 * Get widget storage address
 */
static inline uint32_t gui_external_ram_get_widget_addr() {
    return GUI_WIDGET_STORAGE_ADDR;
}

#endif // GUI_LOADER_EXTERNAL_RAM_H
