/**
 * UI Parser - JSON-based GUI Loader
 *
 * Parses GUI JSON files into widget structures using ArduinoJson
 * Implements the design from docs/discussion_analysis/13_UI_PARSER.md
 * 
 * Generated by Mistral Vibe
 * Date: 2026-08-19
 */

#ifndef UI_PARSER_H
#define UI_PARSER_H

#include <stdint.h>
#include <stdbool.h>
#include "widget_pool.h"

// ============================================================================
// Configuration
// ============================================================================

#define UI_BUFFER_SIZE 2048  // Buffer for UI JSON data

// ============================================================================
// JSON Keys
// ============================================================================

#define JSON_KEY_TYPE "type"
#define JSON_KEY_TEXT "text"
#define JSON_KEY_X "x"
#define JSON_KEY_Y "y"
#define JSON_KEY_WIDTH "width"
#define JSON_KEY_HEIGHT "height"
#define JSON_KEY_STYLE "style"
#define JSON_KEY_CHILDREN "children"
#define JSON_KEY_CALLBACK "callback"
#define JSON_KEY_VALUE "value"
#define JSON_KEY_MIN "min"
#define JSON_KEY_MAX "max"

// ============================================================================
// UI Definition Structure
// ============================================================================

typedef struct {
    char name[32];           // UI name
    Widget* root;            // Root widget
    char* json_data;         // Raw JSON data (if loaded)
    bool loaded;             // Is UI loaded
} UIDefinition;

// ============================================================================
// Function Declarations
// ============================================================================

/**
 * @brief Initialize UI parser
 * @return true on success, false on failure
 */
bool ui_parser_init(void);

/**
 * @brief Shutdown UI parser
 */
void ui_parser_shutdown(void);

/**
 * @brief Parse JSON string to GUI structure
 * @param json JSON string
 * @return Pointer to GUI structure (Widget*), or NULL on error
 * @note Caller must NOT free the returned pointer (managed by pool)
 */
Widget* ui_parse_json(const char* json);

/**
 * @brief Parse widget from JSON object
 * @param json JsonObject from ArduinoJson
 * @param parent Parent widget (can be NULL for root)
 * @return Pointer to widget, or NULL on error
 */
Widget* ui_parse_widget_object(JsonObject json, Widget* parent);

/**
 * @brief Load UI from SD card
 * @param filename GUI filename (e.g., "main_gui.json")
 * @return Pointer to root widget, or NULL on error
 */
Widget* ui_load_from_sd(const char* filename);

/**
 * @brief Load UI from buffer
 * @param json_data JSON string
 * @return Pointer to root widget, or NULL on error
 */
Widget* ui_load_from_buffer(const char* json_data);

/**
 * @brief Free parsed UI
 * @param root Root widget to free
 */
void ui_free(Widget* root);

/**
 * @brief Convert widget tree to JSON string
 * @param root Root widget
 * @return JSON string (caller must free), or NULL on error
 */
char* ui_to_json(Widget* root);

/**
 * @brief Convert widget to JSON object
 * @param widget Widget to convert
 * @param json JsonObject to populate
 */
void ui_widget_to_json(Widget* widget, JsonObject json);

/**
 * @brief Get callback function by name
 * @param name Callback name
 * @return Function pointer, or NULL if not found
 */
void (*ui_get_callback(const char* name))(void);

/**
 * @brief Parse common widget properties
 * @param widget Widget to populate
 * @param json JsonObject containing properties
 */
void ui_parse_common_properties(Widget* widget, JsonObject json);

/**
 * @brief Convert string to WIDGET_TYPE
 * @param str Type string (e.g., "button", "label")
 * @return WIDGET_TYPE enum value
 */
WIDGET_TYPE ui_string_to_widget_type(const char* str);

/**
 * @brief Convert WIDGET_TYPE to string
 * @param type WIDGET_TYPE enum value
 * @return Type string (e.g., "button", "label")
 */
const char* ui_widget_type_to_string(WIDGET_TYPE type);

// ============================================================================
// Type-specific parsers
// ============================================================================

Widget* ui_parse_view(JsonObject json, Widget* parent);
WidgetButton* ui_parse_button(JsonObject json, Widget* parent);
WidgetLabel* ui_parse_label(JsonObject json, Widget* parent);
WidgetSlider* ui_parse_slider(JsonObject json, Widget* parent);

// ============================================================================
// Validation
// ============================================================================

/**
 * @brief Validate GUI JSON
 * @param json JSON string to validate
 * @return true if valid, false otherwise
 */
bool ui_validate_json(const char* json);

#endif // UI_PARSER_H
