/**
 * GUIKit Bootloader Header
 * 
 * Hardware detection and memory strategy initialization at boot
 * 
 * Generated by Mistral Vibe
 * Date: 2026-08-15
 */

#ifndef GUIKIT_BOOTLOADER_H
#define GUIKIT_BOOTLOADER_H

#include <stdint.h>
#include <stdbool.h>
#include "guikit_hw_config.h"

// Forward declarations
class SPISRAM;
class SDCard;
class TFT_ST7789;

// ============================================================================
// Hardware Detection Structures
// ============================================================================

/**
 * Information about detected hardware
 */
typedef struct {
    // RAM
    bool sram_detected;           ///< True if SPI SRAM is detected
    uint32_t sram_size;           ///< Size of detected SRAM in bytes
    uint8_t sram_cs_pin;           ///< CS pin for SRAM
    const char* sram_type;        ///< Type of SRAM (e.g., "23LC1024")
    
    bool psram_detected;          ///< True if PSRAM is detected
    uint32_t psram_size;          ///< Size of detected PSRAM in bytes
    
    // Storage
    bool sdcard_detected;        ///< True if SD Card is detected
    uint8_t sdcard_cs_pin;         ///< CS pin for SD Card
    
    // Display
    bool tft_detected;            ///< True if TFT display is detected
    uint16_t tft_width;           ///< TFT width in pixels
    uint16_t tft_height;          ///< TFT height in pixels
    uint8_t tft_cs_pin;           ///< CS pin for TFT
    
    // Input
    bool touch_detected;         ///< True if touch controller is detected
    uint8_t touch_cs_pin;          ///< CS pin for touch controller
    
    // Expansion
    uint8_t spi_expander_count;   ///< Number of SPI expanders detected
    uint16_t total_expander_gpio;  ///< Total GPIO from all expanders
    
    // Network
    bool webdav_available;        ///< True if WebDAV is available
    
} BootHardwareInfo;

// ============================================================================
// Kernel Check Structures
// ============================================================================

/**
 * Kernel information
 */
typedef struct {
    bool found;                    ///< True if kernel file is found
    const char* path;              ///< Path to kernel file
    uint32_t size;                 ///< Size of kernel in bytes
    const char* version;           ///< Kernel version string
    bool fits_in_ram;              ///< True if kernel fits in available RAM
    uint32_t required_ram;          ///< RAM required for kernel
    MemoryStrategyLevel strategy;  ///< Strategy that can load this kernel
} KernelInfo;

// ============================================================================
// Bootloader State
// ============================================================================

/**
 * Bootloader states
 */
typedef enum {
    BOOT_STATE_INIT = 0,              ///< Initial state
    BOOT_STATE_HARDWARE_DETECTION,   ///< Detecting hardware
    BOOT_STATE_RAM_INITIALIZATION,   ///< Initializing RAM
    BOOT_STATE_SPI_DETECTION,        ///< Detecting SPI devices
    BOOT_STATE_SDCARD_DETECTION,     ///< Detecting SD Card
    BOOT_STATE_TFT_INITIALIZATION,   ///< Initializing TFT
    BOOT_STATE_KERNEL_CHECK,         ///< Checking kernel file
    BOOT_STATE_MEMORY_STRATEGY_CONFIG,  ///< Configuring memory strategy
    BOOT_STATE_MEMORY_STRATEGY_APPLY,    ///< Applying memory strategy
    BOOT_STATE_DISPLAY_RESULTS,      ///< Displaying results
    BOOT_STATE_COMPLETE,             ///< Boot complete
    BOOT_STATE_ERROR                 ///< Error occurred
} BootState;

/**
 * Complete bootloader state
 */
typedef struct {
    BootState current_state;          ///< Current boot state
    BootState last_error_state;       ///< State where error occurred
    const char* error_message;        ///< Error message (if any)
    
    // Hardware detection results
    BootHardwareInfo hardware;        ///< Detected hardware information
    
    // Kernel check results
    KernelInfo kernel;                ///< Kernel file information
    
    // Memory strategy results
    MemoryStrategyLevel selected_strategy;  ///< Selected memory strategy
    uint32_t available_ram;            ///< Total available RAM in bytes
    uint32_t available_external_ram;  ///< Available external RAM in bytes
    uint32_t available_sd_swap;        ///< Available SD swap in bytes
    
    // Configuration
    guikit_hw_config_t config;        ///< Platform configuration
    memory_strategy_config_t memory_config;  ///< Memory strategy configuration
    
    // Hardware instances (platform-specific objects)
    SPISRAM* sram_instance;          ///< SRAM instance
    SDCard* sdcard_instance;         ///< SD Card instance
    TFT_ST7789* tft_instance;        ///< TFT display instance
    
    // Timing
    uint32_t boot_start_time;        ///< Boot start time (ms)
    uint32_t boot_end_time;          ///< Boot end time (ms)
    
} BootloaderState;

// ============================================================================
// Bootloader Functions
// ============================================================================

/**
 * @brief Initialize bootloader state
 * 
 * @param state Bootloader state to initialize
 * @param platform_config Platform configuration to use (can be NULL for defaults)
 */
void bootloader_init(BootloaderState* state, const guikit_hw_config_t* platform_config);

/**
 * @brief Run the complete bootloader sequence
 * 
 * This function performs the following steps:
 * 1. Hardware detection (SPI devices: SRAM, PSRAM, SD Card, TFT, Touch, Expanders)
 * 2. RAM initialization
 * 3. SD Card initialization
 * 4. TFT initialization
 * 5. Memory strategy configuration based on detected hardware
 * 6. Memory strategy testing and application
 * 7. Display results on TFT (if available)
 * 
 * @param state Bootloader state (initialized by bootloader_init)
 * @return true on success, false on failure
 */
bool guikit_bootloader_run(BootloaderState* state);

/**
 * @brief Configure memory strategy based on detected hardware
 * 
 * This function automatically configures the memory strategy thresholds
 * based on what hardware is detected:
 * - If external RAM is available, it will be used for larger GUIs
 * - If SD Card is available, SD swap will be enabled
 * - Thresholds are adjusted based on available RAM
 * 
 * @param state Bootloader state with detected hardware
 */
void configure_memory_strategy(BootloaderState* state);

/**
 * @brief Detect SPI devices and populate hardware info
 * 
 * @param state Bootloader state to populate with hardware info
 */
void detect_spi_devices(BootloaderState* state);

/**
 * @brief Initialize RAM (internal and external)
 * 
 * @param state Bootloader state
 * @return true on success, false on failure
 */
bool init_ram(BootloaderState* state);

/**
 * @brief Initialize SD Card
 * 
 * @param state Bootloader state
 * @return true on success, false on failure
 */
bool init_sd_card(BootloaderState* state);

/**
 * @brief Initialize TFT display
 * 
 * @param state Bootloader state
 * @return true on success, false on failure
 */
bool init_tft(BootloaderState* state);

/**
 * @brief Test memory strategy with various GUI sizes
 * 
 * @param state Bootloader state
 */
void test_memory_strategy(BootloaderState* state);

// ============================================================================
// Kernel Check Functions
// ============================================================================

/**
 * @brief Check if kernel file exists and is accessible
 * 
 * @param state Bootloader state
 * @param kernel_path Path to kernel file (e.g., "/kernel.bin")
 * @return true if kernel is found and accessible
 */
bool check_kernel_exists(BootloaderState* state, const char* kernel_path);

/**
 * @brief Get kernel file size
 * 
 * @param state Bootloader state
 * @param kernel_path Path to kernel file
 * @return Kernel size in bytes, or 0 if not found
 */
uint32_t get_kernel_size(BootloaderState* state, const char* kernel_path);

/**
 * @brief Check if kernel fits in available RAM
 * 
 * This function checks if the kernel can be loaded into the available RAM
 * using the current memory strategy configuration.
 * 
 * @param state Bootloader state with RAM info
 * @param kernel_size Size of kernel in bytes
 * @return true if kernel fits in available RAM
 */
bool check_kernel_fits_in_ram(BootloaderState* state, uint32_t kernel_size);

/**
 * @brief Determine which strategy can load the kernel
 * 
 * @param state Bootloader state with hardware and memory config
 * @param kernel_size Size of kernel in bytes
 * @return MemoryStrategyLevel that can load the kernel, or FAILED
 */
MemoryStrategyLevel determine_kernel_strategy(BootloaderState* state, uint32_t kernel_size);

/**
 * @brief Check kernel file and update state
 * 
 * This function:
 * 1. Checks if kernel file exists
 * 2. Gets kernel size
 * 3. Checks if kernel fits in available RAM
 * 4. Determines which strategy can load it
 * 5. Updates state->kernel with results
 * 
 * @param state Bootloader state
 * @param kernel_path Path to kernel file
 * @return true if kernel is valid and can be loaded
 */
bool check_kernel(BootloaderState* state, const char* kernel_path);

// ============================================================================
// Hardware Detection Functions
// (These are mock implementations - replace with actual hardware code)
// ============================================================================

/**
 * @brief Detect SPI SRAM (23LC1024) at specified CS pin
 * 
 * @param cs_pin Chip select pin
 * @param size Output: Size of SRAM in bytes
 * @param type Output: Type of SRAM as string
 * @return true if SRAM is detected, false otherwise
 */
bool detect_spi_sram(uint8_t cs_pin, uint32_t* size, const char** type);

/**
 * @brief Detect SPI PSRAM at specified CS pin
 * 
 * @param cs_pin Chip select pin
 * @param size Output: Size of PSRAM in bytes
 * @return true if PSRAM is detected, false otherwise
 */
bool detect_spi_psram(uint8_t cs_pin, uint32_t* size);

/**
 * @brief Detect SD Card at specified CS pin
 * 
 * @param cs_pin Chip select pin
 * @return true if SD Card is detected, false otherwise
 */
bool detect_sd_card(uint8_t cs_pin);

/**
 * @brief Detect TFT display at specified CS pin
 * 
 * @param cs_pin Chip select pin
 * @param width Output: TFT width in pixels
 * @param height Output: TFT height in pixels
 * @return true if TFT is detected, false otherwise
 */
bool detect_tft(uint8_t cs_pin, uint16_t* width, uint16_t* height);

/**
 * @brief Detect Touch controller at specified CS pin
 * 
 * @param cs_pin Chip select pin
 * @return true if touch controller is detected, false otherwise
 */
bool detect_touch(uint8_t cs_pin);

/**
 * @brief Detect SPI expander (MCP23S17, etc.) at specified CS pin
 * 
 * @param cs_pin Chip select pin
 * @param exp_type Output: Type of expander
 * @return true if expander is detected, false otherwise
 */
bool detect_spi_expander(uint8_t cs_pin, guikit_expander_type_t* exp_type);

// ============================================================================
// Display Functions
// (These are mock implementations - replace with actual TFT code)
// ============================================================================

/**
 * @brief Initialize TFT display
 * 
 * @param tft Output: TFT instance
 * @param cs_pin Chip select pin
 * @param width TFT width
 * @param height TFT height
 * @return true on success, false on failure
 */
bool tft_init(TFT_ST7789** tft, uint8_t cs_pin, uint16_t width, uint16_t height);

/**
 * @brief Clear TFT screen
 * 
 * @param tft TFT instance
 * @param color Background color
 */
void tft_clear(TFT_ST7789* tft, uint16_t color);

/**
 * @brief Draw text on TFT
 * 
 * @param tft TFT instance
 * @param x X position
 * @param y Y position
 * @param text Text to draw
 * @param color Text color
 * @param bg_color Background color
 */
void tft_draw_text(TFT_ST7789* tft, int x, int y, const char* text, uint16_t color, uint16_t bg_color);

/**
 * @brief Draw progress bar on TFT
 * 
 * @param tft TFT instance
 * @param x X position
 * @param y Y position
 * @param width Width of progress bar
 * @param height Height of progress bar
 * @param percent Completion percentage (0-100)
 * @param color Progress bar color
 */
void tft_draw_progress(TFT_ST7789* tft, int x, int y, int width, int height, int percent, uint16_t color);

#endif // GUIKIT_BOOTLOADER_H
