/**
 * @brief RAM Length Detection and Testing
 * 
 * Implements RAM length detection to verify actual RAM size
 * and detect wiring errors (e.g., 64K chip wired as 256K).
 * 
 * Features:
 * - 1 or 2 pass testing for reliability
 * - Progress display on TFT
 * - Warning for mismatched RAM sizes
 * - Timeout handling
 * 
 * Generated by Mistral Vibe
 * Date: 2026-08-16
 */

#ifndef GUIKIT_RAM_TEST_H
#define GUIKIT_RAM_TEST_H

#include <stdint.h>
#include <stdbool.h>

// ============================================================================
// RAM Test Result Structure
// ============================================================================

typedef enum {
    RAM_TEST_OK = 0,              /// Test passed, RAM size matches expected
    RAM_TEST_SIZE_MISMATCH,       /// Detected size doesn't match expected
    RAM_TEST_FAILED,              /// Test failed (read/write error)
    RAM_TEST_TIMEOUT,             /// Test timed out
    RAM_TEST_NOT_DETECTED         /// No RAM detected
} RamTestResult;

typedef struct {
    RamTestResult result;         /// Test result
    uint32_t detected_size;        /// Actually detected RAM size in bytes
    uint32_t expected_size;        /// Expected RAM size from config (0 = auto)
    uint8_t test_passes;          /// Number of passes performed
    uint32_t test_time_ms;        /// Time taken for test in ms
    const char* chip_type;         /// Detected chip type string
    uint8_t cs_pin;               /// CS pin for this RAM bank
    const char* error_message;     /// Error message if test failed
} RamTestInfo;

// ============================================================================
// RAM Test Configuration
// ============================================================================

typedef struct {
    bool enabled;                 /// Enable RAM testing
    uint8_t passes;                /// Number of test passes (1 or 2)
    uint32_t timeout_ms;           /// Timeout in milliseconds
    bool show_progress;            /// Show progress on TFT
    bool stop_on_failure;          /// Stop boot on failure
    uint32_t expected_size;        /// Expected size (0 = auto-detect only)
} RamTestConfig;

// ============================================================================
// Test Pattern Definitions
// ============================================================================

/// Pattern 1: 0xAA (10101010) - Good for detecting stuck bits
#define RAM_TEST_PATTERN_1 0xAA

/// Pattern 2: 0x55 (01010101) - Complement of pattern 1
#define RAM_TEST_PATTERN_2 0x55

/// Pattern 3: 0xFF (11111111) - All ones
#define RAM_TEST_PATTERN_3 0xFF

/// Pattern 4: 0x00 (00000000) - All zeros
#define RAM_TEST_PATTERN_4 0x00

/// Address increment for testing (test every N bytes for speed)
#define RAM_TEST_STEP_SIZE 256

// ============================================================================
// RAM Size Detection Constants
// ============================================================================

/// Common RAM chip sizes in bytes
#define RAM_SIZE_8KB      8192
#define RAM_SIZE_16KB     16384
#define RAM_SIZE_32KB     32768
#define RAM_SIZE_64KB     65536
#define RAM_SIZE_128KB    131072
#define RAM_SIZE_256KB    262144
#define RAM_SIZE_512KB    524288
#define RAM_SIZE_1MB      1048576
#define RAM_SIZE_2MB      2097152
#define RAM_SIZE_4MB      4194304
#define RAM_SIZE_8MB      8388608
#define RAM_SIZE_16MB     16777216
#define RAM_SIZE_32MB     33554432
#define RAM_SIZE_64MB     67108864

/// Known RAM chip sizes for auto-detection
static const uint32_t KNOWN_RAM_SIZES[] = {
    RAM_SIZE_64MB,    // ISSI IS66WVS5128ALL/BLL
    RAM_SIZE_8MB,     // W9812G6KH PSRAM
    RAM_SIZE_512KB,   // LY68L6400, CY15V104QSN
    RAM_SIZE_256KB,   // 23LC256 (if exists)
    RAM_SIZE_128KB,   // 23LC1024, CY15V102QN, MB85RS1MV
    RAM_SIZE_64KB,    // 23LC640, MB85RS64B
    RAM_SIZE_32KB,    // 23K256, MB85RC512V
    RAM_SIZE_16KB,    // (less common)
    RAM_SIZE_8KB      // (less common)
};

// ============================================================================
// Function Declarations
// ============================================================================

/// @brief Test RAM at specified CS pin and determine its actual size
/// @param cs_pin Chip select pin
/// @param config Test configuration
/// @param info Output test information
/// @return Test result
RamTestResult ram_test_detect_size(uint8_t cs_pin, const RamTestConfig* config, RamTestInfo* info);

/// @brief Test a specific RAM address range
/// @param cs_pin Chip select pin
/// @param start_addr Start address
/// @param end_addr End address
/// @param pattern Test pattern to write
/// @return true if test passed
bool ram_test_address_range(uint8_t cs_pin, uint32_t start_addr, uint32_t end_addr, uint8_t pattern);

/// @brief Write a byte to RAM via SPI
/// @param cs_pin Chip select pin
/// @param addr Address to write to
/// @param data Byte to write
/// @return true on success
bool ram_write_byte(uint8_t cs_pin, uint32_t addr, uint8_t data);

/// @brief Read a byte from RAM via SPI
/// @param cs_pin Chip select pin
/// @param addr Address to read from
/// @return Byte read (0xFF on error)
uint8_t ram_read_byte(uint8_t cs_pin, uint32_t addr);

/// @brief Find the actual size of RAM by binary search
/// @param cs_pin Chip select pin
/// @param max_possible_size Maximum size to test
/// @param passes Number of test passes
/// @return Detected RAM size in bytes
uint32_t ram_find_actual_size(uint8_t cs_pin, uint32_t max_possible_size, uint8_t passes);

/// @brief Display RAM test progress on TFT
/// @param progress Percent complete (0-100)
/// @param current_size Current size being tested in bytes
/// @param message Progress message
void ram_test_display_progress(uint8_t progress, uint32_t current_size, const char* message);

/// @brief Display RAM test result
/// @param info Test information
void ram_test_display_result(const RamTestInfo* info);

/// @brief Format RAM size as human-readable string
/// @param size Size in bytes
/// @param buffer Output buffer
/// @param buffer_size Buffer size
void ram_format_size(uint32_t size, char* buffer, uint32_t buffer_size);

/// @brief Get RAM size name (e.g., "128KB", "512KB")
/// @param size Size in bytes
/// @return Size name string
const char* ram_size_name(uint32_t size);

#endif // GUIKIT_RAM_TEST_H
