/**
 * @file task_switcher_example.c
 * @brief Example Implementation: JPEG to RGB Conversion
 * 
 * Demonstrates task switching with JPEG to RGB conversion.
 * 
 * Generated by Mistral Vibe
 * Date: 2026-08-16
 */

#include "task_switcher_example.h"
#include "task_switcher.h"
#include "crc32.h"
#include <string.h>
#include <stdio.h>

// ============================================================================
// TASK A: GUI IMAGE VIEWER IMPLEMENTATION
// ============================================================================

bool gui_trigger_jpeg_conversion(const char* jpeg_path) {
    if (!jpeg_path || !jpeg_path[0]) {
        printf("[GUI] ERROR: No JPEG path specified\n");
        return false;
    }
    
    printf("[GUI] Starting JPEG conversion: %s\n", jpeg_path);
    printf("[GUI] Freezing current state and switching to converter...\n");
    
    // Switch to JPEG converter task
    // The task switcher will automatically freeze this task's RAM
    bool result = task_switch_to(JPEG_CONVERTER_KERNEL);
    
    if (!result) {
        TaskSwitcherError err = task_switcher_get_error();
        printf("[GUI] ERROR: Failed to switch to converter: %s\n", 
               task_switcher_error_to_string(err));
        return false;
    }
    
    // In real implementation, this function would not return
    // The new task (JPEG converter) would be running
    // When the user clicks "Back" in the converter, task_restore() is called
    // and execution returns here
    
    printf("[GUI] Resumed after conversion\n");
    return true;
}

uint32_t gui_load_conversion_result(RgbImageHeader* header, 
                                   uint8_t* rgb_buffer, 
                                   uint32_t buffer_size) {
    if (!header || !rgb_buffer || buffer_size == 0) {
        printf("[GUI] ERROR: Invalid parameters\n");
        return 0;
    }
    
    // Check if conversion was completed
    if (!task_child_has_file("converted.rgb")) {
        printf("[GUI] No conversion result found\n");
        return 0;
    }
    
    printf("[GUI] Loading conversion result...\n");
    
    // Load header
    uint32_t header_size = sizeof(RgbImageHeader);
    uint32_t bytes_read = task_load_from_child("converted.hdr", 
                                                (void*)header, 
                                                header_size);
    
    if (bytes_read != header_size) {
        printf("[GUI] ERROR: Failed to load header\n");
        return 0;
    }
    
    // Validate header
    if (header->bits_per_pixel != 24) {
        printf("[GUI] ERROR: Unsupported BPP: %u\n", header->bits_per_pixel);
        return 0;
    }
    
    // Load RGB data
    uint32_t data_to_read = (header->data_size < buffer_size) ? 
                            header->data_size : buffer_size;
    
    bytes_read = task_load_from_child("converted.rgb", 
                                     (void*)rgb_buffer, 
                                     data_to_read);
    
    if (bytes_read == 0) {
        printf("[GUI] ERROR: Failed to load RGB data\n");
        return 0;
    }
    
    // Verify CRC32 if needed
    if (header->crc32 != 0) {
        uint32_t calculated_crc = crc32(0xFFFFFFFF, rgb_buffer, bytes_read) ^ 0xFFFFFFFF;
        if (calculated_crc != header->crc32) {
            printf("[GUI] WARNING: CRC32 mismatch! (expected %08lX, got %08lX)\n", 
                   header->crc32, calculated_crc);
        }
    }
    
    printf("[GUI] Loaded %u bytes of RGB data (%ux%u, %u bpp)\n", 
           bytes_read, header->width, header->height, header->bits_per_pixel);
    
    return bytes_read;
}

void gui_cleanup_conversion(void) {
    printf("[GUI] Cleaning up conversion files...\n");
    
    // Delete temporary files
    // In real implementation, use SD card delete functions
    // sd_delete_file(JPEG_OUTPUT_FILE);
    // sd_delete_file("/tmp/converted.hdr");
    // sd_delete_file(JPEG_RESULT_FLAG);
    
    printf("[GUI] Conversion files cleaned up\n");
}

// ============================================================================
// TASK B: JPEG CONVERTER IMPLEMENTATION
// ============================================================================

bool jpeg_converter_run(const char* jpeg_path) {
    if (!jpeg_path || !jpeg_path[0]) {
        printf("[CONVERTER] ERROR: No JPEG path specified\n");
        return false;
    }
    
    printf("[CONVERTER] Starting JPEG to RGB conversion\n");
    printf("[CONVERTER] Input: %s\n", jpeg_path);
    printf("[CONVERTER] Output: %s\n", JPEG_OUTPUT_FILE);
    
    // Perform conversion
    bool result = jpeg_to_rgb_convert(jpeg_path, 
                                      JPEG_OUTPUT_FILE,
                                      "/tmp/converted.hdr");
    
    if (result) {
        printf("[CONVERTER] Conversion complete!\n");
        
        // Create a flag file to indicate completion
        const char* flag = "DONE";
        task_save_for_parent("conversion_done.flag", (const void*)flag, 4);
        
        printf("[CONVERTER] Saved results. Ready to return to GUI.\n");
        printf("[CONVERTER] User should click 'Back' to return.\n");
    } else {
        printf("[CONVERTER] ERROR: Conversion failed\n");
    }
    
    return result;
}

bool jpeg_to_rgb_convert(const char* jpeg_path, 
                        const char* rgb_path, 
                        const char* header_path) {
    // In a real implementation, this would use a JPEG decoder library
    // For example: TinyJPEG, JPEGLIB, or platform-specific decoder
    
    // This is a MOCK implementation that demonstrates the pattern
    
    printf("[CONVERTER] Decoding JPEG: %s\n", jpeg_path);
    
    // Simulate JPEG decoding
    // In real code:
    // 1. Open JPEG file from SD card
    // 2. Decode to RGB
    // 3. Get width, height, data
    
    // MOCK: Create a dummy RGB image
    uint16_t width = 800;
    uint16_t height = 600;
    uint8_t bpp = 24;  // RGB888
    uint32_t data_size = width * height * (bpp / 8);
    
    printf("[CONVERTER] Image: %ux%u, %u bpp\n", width, height, bpp);
    printf("[CONVERTER] RGB data size: %u bytes\n", data_size);
    
    // Allocate and fill with test pattern (in real code, this is actual RGB data)
    uint8_t* rgb_data = (uint8_t*)malloc(data_size);
    if (!rgb_data) {
        printf("[CONVERTER] ERROR: Failed to allocate RGB buffer\n");
        return false;
    }
    
    // Fill with gradient pattern for demo
    for (uint32_t i = 0; i < data_size; i += 3) {
        rgb_data[i] = (uint8_t)(i % 256);     // R
        rgb_data[i+1] = (uint8_t)((i/2) % 256); // G  
        rgb_data[i+2] = (uint8_t)((i/3) % 256); // B
    }
    
    // Create header
    RgbImageHeader header;
    header.width = width;
    header.height = height;
    header.bits_per_pixel = bpp;
    header.data_size = data_size;
    header.crc32 = crc32(0xFFFFFFFF, rgb_data, data_size) ^ 0xFFFFFFFF;
    
    printf("[CONVERTER] CRC32: %08lX\n", header.crc32);
    
    // Save header
    if (!task_save_for_parent("converted.hdr", (const void*)&header, sizeof(header))) {
        printf("[CONVERTER] ERROR: Failed to save header\n");
        free(rgb_data);
        return false;
    }
    
    // Save RGB data
    if (!task_save_for_parent("converted.rgb", (const void*)rgb_data, data_size)) {
        printf("[CONVERTER] ERROR: Failed to save RGB data\n");
        free(rgb_data);
        return false;
    }
    
    free(rgb_data);
    printf("[CONVERTER] Successfully saved RGB data\n");
    
    return true;
}

// ============================================================================
// HELPER FUNCTIONS FOR INTEGRATION
// ============================================================================

/// @brief Example: Back button handler that calls task_restore()
/// 
/// This would be called from your GUI event loop when user clicks "Back"
void handle_back_button(void) {
    if (task_has_frozen_parent()) {
        printf("[GUI] Back button pressed, restoring parent task...\n");
        bool result = task_restore();
        if (!result) {
            printf("[GUI] ERROR: Failed to restore: %s\n", 
                   task_switcher_error_to_string(task_switcher_get_error()));
        }
    } else {
        printf("[GUI] No parent task to restore\n");
    }
}

/// @brief Example: Main loop that checks for conversion results
void gui_main_loop(void) {
    // Check if we just returned from a child task
    if (task_has_frozen_parent()) {
        // We are the child task (converter)
        // Run converter and wait for back button
        jpeg_converter_run(JPEG_INPUT_FILE);
        
        // In real code, you'd have an event loop here
        // while (1) {
        //     check_input();
        //     if (back_button_pressed) {
        //         task_restore();
        //     }
        // }
    } else {
        // We are the parent task (GUI)
        // Check for conversion results
        RgbImageHeader header;
        uint8_t rgb_buffer[1024 * 100];  // Small buffer for demo
        uint32_t loaded = gui_load_conversion_result(&header, rgb_buffer, sizeof(rgb_buffer));
        
        if (loaded > 0) {
            printf("[GUI] Displaying converted image...\n");
            // display_image(&header, rgb_buffer);
            gui_cleanup_conversion();
        }
    }
}
