/**
 * @file task_progress.c
 * @brief Progress Display Implementation for Heavy Tasks
 * 
 * Lightweight progress display on TFT for heavy tasks.
 * Designed to use minimal RAM (< 1KB) and work when only 10KB is available.
 * 
 * Uses TFT functions from guikit_bootloader.h
 * 
 * Generated by Mistral Vibe
 * Date: 2026-08-16
 */

#include "task_progress.h"
#include "guikit_bootloader.h"
#include <string.h>
#include <stdio.h>

// ============================================================================
// GLOBAL STATE (single static instance - no heap allocation)
// ============================================================================

static TaskProgressState g_state;
static bool g_initialized = false;

// ============================================================================
// INTERNAL HELPER FUNCTIONS
// ============================================================================

/// @brief Get TFT instance (from bootloader state)
/// @return void* or NULL if not initialized
static void* get_tft_instance(void) {
    // In real implementation, this would get from bootloader state
    // For now, we use a simple approach
    static void* s_tft = NULL;
    return s_tft;
}

/// @brief Set TFT instance
/// @param tft TFT instance pointer
static void set_tft_instance(void* tft) {
    static void** s_tft_ptr = NULL;
    if (s_tft_ptr) {
        *s_tft_ptr = tft;
    } else {
        s_tft_ptr = &tft;
    }
}

/// @brief Format progress message with percentage
/// @param message Base message
/// @param percent Current percentage
/// @param buffer Output buffer (must be at least 64 bytes)
static void format_progress_message(const char* message, uint8_t percent, char* buffer) {
    if (message) {
        snprintf(buffer, 64, "%s: %u%%", message, percent);
    } else {
        snprintf(buffer, 64, "Progress: %u%%", percent);
    }
}

// ============================================================================
// GLOBAL STATE ACCESSOR
// ============================================================================

TaskProgressState* task_progress_get_state(void) {
    if (!g_initialized) {
        memset(&g_state, 0, sizeof(g_state));
        g_state.x = PROGRESS_X;
        g_state.y = PROGRESS_Y;
        g_state.bar_x = PROGRESS_BAR_X;
        g_state.bar_y = PROGRESS_BAR_Y;
        g_state.bar_width = PROGRESS_BAR_WIDTH;
        g_state.bar_height = PROGRESS_BAR_HEIGHT;
        g_state.fg_color = PROGRESS_BAR_COLOR;
        g_state.bg_color = PROGRESS_BG_COLOR;
        g_state.text_color = PROGRESS_TEXT_COLOR;
        g_initialized = true;
    }
    return &g_state;
}

// ============================================================================
// INITIALIZATION
// ============================================================================

void task_progress_init(bool show_bar, bool show_text) {
    TaskProgressState* state = task_progress_get_state();
    state->active = true;
    state->show_bar = show_bar;
    state->show_text = show_text;
    state->current_percent = 0;
    state->max_percent = 100;
    state->message[0] = '\0';
}

void task_progress_init_custom(int16_t x, int16_t y,
                               int16_t bar_x, int16_t bar_y,
                               bool show_bar, bool show_text) {
    TaskProgressState* state = task_progress_get_state();
    state->active = true;
    state->x = x;
    state->y = y;
    state->bar_x = bar_x;
    state->bar_y = bar_y;
    state->show_bar = show_bar;
    state->show_text = show_text;
    state->current_percent = 0;
    state->max_percent = 100;
    state->message[0] = '\0';
}

void task_progress_done(void) {
    TaskProgressState* state = task_progress_get_state();
    if (state->active) {
        // Clear any displayed progress
        if (state->show_text) {
            task_progress_text_clear();
        }
        if (state->show_bar) {
            void* tft = get_tft_instance();
            if (tft) {
                // Cast to TFT_ST7789* for the draw function
                tft_draw_progress((TFT_ST7789*)tft, state->bar_x, state->bar_y, 
                                  state->bar_width, state->bar_height, 
                                  0, state->bg_color);
            }
        }
        state->active = false;
    }
}

// ============================================================================
// PROGRESS DISPLAY
// ============================================================================

void task_progress_start(const char* message, uint8_t max) {
    TaskProgressState* state = task_progress_get_state();
    state->active = true;
    state->current_percent = 0;
    state->max_percent = max > 0 ? max : 100;
    
    if (message) {
        strncpy(state->message, message, sizeof(state->message) - 1);
        state->message[sizeof(state->message) - 1] = '\0';
    } else {
        state->message[0] = '\0';
    }
    
    // Draw initial progress
    task_progress_update(0);
}

void task_progress_update(uint8_t current) {
    TaskProgressState* state = task_progress_get_state();
    if (!state->active) return;
    
    state->current_percent = (current > state->max_percent) ? state->max_percent : current;
    
    void* tft = get_tft_instance();
    if (!tft) return;
    
    // Update text
    if (state->show_text) {
        char buffer[64];
        format_progress_message(state->message[0] ? state->message : NULL, 
                               state->current_percent, buffer);
        tft_draw_text((TFT_ST7789*)tft, state->x, state->y, buffer, 
                      state->text_color, state->bg_color);
    }
    
    // Update bar
    if (state->show_bar) {
        tft_draw_progress((TFT_ST7789*)tft, state->bar_x, state->bar_y,
                          state->bar_width, state->bar_height,
                          state->current_percent, state->fg_color);
    }
}

void task_progress_update_msg(uint8_t current, const char* message) {
    TaskProgressState* state = task_progress_get_state();
    if (!state->active) return;
    
    if (message) {
        strncpy(state->message, message, sizeof(state->message) - 1);
        state->message[sizeof(state->message) - 1] = '\0';
    }
    
    task_progress_update(current);
}

void task_progress_inc(void) {
    TaskProgressState* state = task_progress_get_state();
    if (!state->active) return;
    
    uint8_t next = state->current_percent + 1;
    if (next > state->max_percent) next = state->max_percent;
    task_progress_update(next);
}

void task_progress_complete(void) {
    TaskProgressState* state = task_progress_get_state();
    if (!state->active) return;
    
    task_progress_update(state->max_percent);
}

// ============================================================================
// SIMPLE TEXT-ONLY PROGRESS
// ============================================================================

void task_progress_text(const char* message, uint8_t percent) {
    void* tft = get_tft_instance();
    if (!tft) return;
    
    char buffer[64];
    format_progress_message(message, percent, buffer);
    tft_draw_text((TFT_ST7789*)tft, PROGRESS_X, PROGRESS_Y, buffer, 
                  PROGRESS_TEXT_COLOR, PROGRESS_BG_COLOR);
}

void task_progress_text_clear(void) {
    void* tft = get_tft_instance();
    if (!tft) return;
    
    // Clear the text area by drawing a black rectangle
    // For simplicity, we redraw the text with empty message
    tft_draw_text((TFT_ST7789*)tft, PROGRESS_X, PROGRESS_Y, "                    ", 
                  PROGRESS_BG_COLOR, PROGRESS_BG_COLOR);
}

// ============================================================================
// LOW-RAM VERSIONS (< 10KB available)
// ============================================================================

/// @brief Internal TFT pointer for minimal mode (static to avoid heap)
static void* s_minimal_tft = NULL;

void task_progress_minimal(const char* message, uint8_t percent) {
    // This function uses ONLY stack - no heap allocation
    // Uses ~100 bytes of stack maximum
    
    if (!s_minimal_tft) {
        // Try to get TFT instance
        s_minimal_tft = get_tft_instance();
        if (!s_minimal_tft) {
            // Fallback: just return, no TFT available
            return;
        }
    }
    
    // Format message directly on stack
    char buffer[64];  // Stack-allocated buffer
    format_progress_message(message, percent, buffer);
    
    // Draw text at default position with default colors
    tft_draw_text((TFT_ST7789*)s_minimal_tft, PROGRESS_X, PROGRESS_Y, buffer,
                  PROGRESS_TEXT_COLOR, PROGRESS_BG_COLOR);
}

void task_progress_minimal_clear(void) {
    if (s_minimal_tft) {
        // Clear by drawing spaces
        tft_draw_text((TFT_ST7789*)s_minimal_tft, PROGRESS_X, PROGRESS_Y, "                    ",
                      PROGRESS_BG_COLOR, PROGRESS_BG_COLOR);
        s_minimal_tft = NULL;
    }
}

// ============================================================================
// TFT INSTANCE MANAGEMENT
// ============================================================================

/// @brief Set the TFT instance for progress display
/// @param tft TFT instance pointer
void task_progress_set_tft(void* tft) {
    set_tft_instance(tft);
    s_minimal_tft = tft;
}

/// @brief Get the current TFT instance
/// @return TFT instance pointer or NULL
void* task_progress_get_tft(void) {
    return get_tft_instance();
}
