/**
 * ESP8266 + MCP23S17 + 23LC1024 + TFT Example Configuration
 * 
 * Example hardware configuration for ESP8266 (NodeMCU v2) with:
 * - MCP23S17 GPIO Expander (16 additional GPIO pins)
 * - 23LC1024 SPI SRAM (128 KB external RAM)
 * - TFT ST7789 Display (320x240)
 * 
 * This example demonstrates how to configure and initialize all three
 * SPI devices on the shared SPI bus of ESP8266.
 * 
 * Wiring:
 * - TFT: CS=D8(GPIO15), DC=D3(GPIO0), RST=D4(GPIO2), SCK=D5, MOSI=D7, MISO=D6
 * - MCP23S17: CS=D2(GPIO4), IRQ=D1(GPIO5), SCK=D5, MOSI=D7, MISO=D6
 * - 23LC1024: CS=D0(GPIO16), SCK=D5, MOSI=D7, MISO=D6
 * 
 * Note: All devices share SCK, MOSI, MISO. Each has unique CS line.
 * 
 * Generated by Mistral Vibe
 * Date: 2026-08-15
 */

#ifndef ESP8266_EXPANDER_RAM_TFT_H
#define ESP8266_EXPANDER_RAM_TFT_H

#include <stdint.h>
#include <stdbool.h>

// ============================================================================
// Pin Definitions for ESP8266 NodeMCU
// ============================================================================

// TFT ST7789 Pins
#define TFT_CS_PIN    15  // D8 (GPIO15)
#define TFT_DC_PIN    0   // D3 (GPIO0)
#define TFT_RST_PIN   2   // D4 (GPIO2)

// MCP23S17 GPIO Expander Pins
#define EXPANDER_CS_PIN   4   // D2 (GPIO4)
#define EXPANDER_IRQ_PIN  5   // D1 (GPIO5) - Optional

// 23LC1024 SRAM Pins
#define SRAM_CS_PIN    16  // D0 (GPIO16)

// Shared SPI Pins
#define SPI_SCK_PIN    14  // D5 (GPIO14)
#define SPI_MOSI_PIN   13  // D7 (GPIO13)
#define SPI_MISO_PIN   12  // D6 (GPIO12)

// SPI Speed
#define SPI_MAX_SPEED_MHZ 20

// ============================================================================
// Configuration Using Union-Based Struct
// ============================================================================

#include "guikit_hw_config_union.h"

// Pre-configured config for ESP8266 + MCP23S17 + 23LC1024 + TFT
 extern const guikit_hw_config_union_t ESP8266_EXPANDER_RAM_TFT_CONFIG;

// ============================================================================
// Configuration Using Simple Struct
// ============================================================================

#include "guikit_hw_config.h"

// Alternative config using simple struct
 extern const guikit_hw_config_t ESP8266_EXPANDER_RAM_TFT_CONFIG_SIMPLE;

// ============================================================================
// Individual Device Configurations
// ============================================================================

// TFT Configuration
typedef struct {
    uint8_t cs_pin;
    uint8_t dc_pin;
    uint8_t rst_pin;
    uint16_t width;
    uint16_t height;
    uint8_t color_depth;  // bits per pixel
    bool double_buffer;
} tft_config_t;

 extern const tft_config_t ESP8266_TFT_CONFIG;

// SRAM Configuration
typedef struct {
    uint8_t cs_pin;
    uint32_t size_bytes;
    uint8_t spi_bus;
} sram_config_t;

 extern const sram_config_t ESP8266_SRAM_CONFIG;

// Expander Configuration
typedef struct {
    uint8_t cs_pin;
    uint8_t irq_pin;
    uint8_t reset_pin;
    uint16_t gpio_count;  // 16 for MCP23S17
} expander_config_t;

 extern const expander_config_t ESP8266_EXPANDER_CONFIG;

// ============================================================================
// Combined Configuration
// ============================================================================

// All hardware configuration in one place
typedef struct {
    tft_config_t tft;
    sram_config_t sram;
    expander_config_t expander;
    
    // SPI bus settings
    uint8_t sck_pin;
    uint8_t mosi_pin;
    uint8_t miso_pin;
    uint8_t max_speed_mhz;
    
    // System settings
    bool use_sd_card;
    bool use_webdav;
    bool debug_mode;
} esp8266_hardware_config_t;

 extern const esp8266_hardware_config_t ESP8266_FULL_CONFIG;

#endif // ESP8266_EXPANDER_RAM_TFT_H
