/**
 * @file webdav_push_auth.c
 * @brief Authentication and Authorization Implementation
 *
 * Provides secure authentication for WebDAV push notification clients.
 * 
 * Features:
 * - Username/password authentication with hashing
 * - Session management with tokens
 * - Permission-based access control
 * - Rate limiting per client
 * - Secure random generation
 *
 * Generated by Mistral Vibe.
 * Date: 2026-08-16
 */

#include "webdav_push_auth.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>

// ============================================================================
// INTERNAL STATE
// ============================================================================

static bool g_auth_initialized = false;
static WebDAVPushAuthConfig g_auth_config;

// Users
static WebDAVPushUser g_users[WEBDAV_PUSH_MAX_USERS];
static uint8_t g_user_count = 0;

// Sessions
static WebDAVPushSession g_sessions[WEBDAV_PUSH_MAX_SESSIONS];
static uint8_t g_session_count = 0;

// Tokens
static WebDAVPushToken g_tokens[WEBDAV_PUSH_MAX_TOKENS];
static uint8_t g_token_count = 0;

// Client auth states
static WebDAVPushAuthState g_auth_states[WEBDAV_PUSH_MAX_CLIENTS];

// Rate limiting
static uint32_t g_notification_counts[WEBDAV_PUSH_MAX_CLIENTS];
static uint64_t g_notification_timestamps[WEBDAV_PUSH_MAX_CLIENTS];

// ============================================================================
// DEFAULT CONFIGURATION
// ============================================================================

static const WebDAVPushAuthConfig DEFAULT_AUTH_CONFIG = {
    .require_auth = true,
    .default_method = WEBDAV_PUSH_AUTH_BASIC,
    .allow_anonymous = false,
    .use_session_tokens = true,
    .token_expiry = 86400000,  // 24 hours in ms
};

// ============================================================================
// INITIALIZATION
// ============================================================================

bool webdav_push_auth_init(const WebDAVPushAuthConfig* config) {
    if (g_auth_initialized) {
        return true;
    }
    
    // Copy configuration
    if (config) {
        g_auth_config = *config;
    } else {
        g_auth_config = DEFAULT_AUTH_CONFIG;
    }
    
    // Initialize users
    for (int i = 0; i < WEBDAV_PUSH_MAX_USERS; i++) {
        g_users[i].username[0] = '\0';
        g_users[i].password_hash[0] = '\0';
        g_users[i].permissions = 0;
        g_users[i].enabled = false;
    }
    
    // Initialize sessions
    for (int i = 0; i < WEBDAV_PUSH_MAX_SESSIONS; i++) {
        g_sessions[i].session_id[0] = '\0';
        g_sessions[i].username[0] = '\0';
        g_sessions[i].client_id = 0;
        g_sessions[i].authenticated = false;
    }
    
    // Initialize tokens
    for (int i = 0; i < WEBDAV_PUSH_MAX_TOKENS; i++) {
        g_tokens[i].token[0] = '\0';
        g_tokens[i].username[0] = '\0';
        g_tokens[i].used = false;
    }
    
    // Initialize auth states
    for (int i = 0; i < WEBDAV_PUSH_MAX_CLIENTS; i++) {
        g_auth_states[i].authenticated = false;
        g_auth_states[i].username[0] = '\0';
        g_auth_states[i].session_id[0] = '\0';
        g_auth_states[i].failed_attempts = 0;
        g_notification_counts[i] = 0;
        g_notification_timestamps[i] = 0;
    }
    
    // Add default admin user
    webdav_push_user_add("admin", "admin", WEBDAV_PUSH_PERM_ALL);
    
    g_auth_initialized = true;
    return true;
}

void webdav_push_auth_shutdown(void) {
    if (!g_auth_initialized) {
        return;
    }
    
    // Clear sensitive data
    for (int i = 0; i < WEBDAV_PUSH_MAX_USERS; i++) {
        // Overwrite password hashes
        memset(g_users[i].password_hash, 0, sizeof(g_users[i].password_hash));
    }
    
    for (int i = 0; i < WEBDAV_PUSH_MAX_SESSIONS; i++) {
        memset(g_sessions[i].session_id, 0, sizeof(g_sessions[i].session_id));
    }
    
    for (int i = 0; i < WEBDAV_PUSH_MAX_TOKENS; i++) {
        memset(g_tokens[i].token, 0, sizeof(g_tokens[i].token));
    }
    
    g_auth_initialized = false;
}

bool webdav_push_auth_required(void) {
    return g_auth_initialized && g_auth_config.require_auth;
}

// ============================================================================
// USER MANAGEMENT
// ============================================================================

bool webdav_push_user_add(const char* username, const char* password, WebDAVPushPermission permissions) {
    if (!g_auth_initialized || !username || !password || g_user_count >= WEBDAV_PUSH_MAX_USERS) {
        return false;
    }
    
    // Check if user already exists
    for (int i = 0; i < g_user_count; i++) {
        if (strcmp(g_users[i].username, username) == 0) {
            return false;  // User exists
        }
    }
    
    // Add new user
    WebDAVPushUser* user = &g_users[g_user_count++];
    strncpy(user->username, username, sizeof(user->username) - 1);
    user->username[sizeof(user->username) - 1] = '\0';
    
    // Hash password
    webdav_push_password_hash(password, user->password_hash);
    
    user->permissions = permissions;
    user->enabled = true;
    
    return true;
}

bool webdav_push_user_remove(const char* username) {
    if (!g_auth_initialized || !username) {
        return false;
    }
    
    for (int i = 0; i < g_user_count; i++) {
        if (strcmp(g_users[i].username, username) == 0) {
            // Clear password hash
            memset(g_users[i].password_hash, 0, sizeof(g_users[i].password_hash));
            
            // Compact array
            for (int j = i; j < g_user_count - 1; j++) {
                g_users[j] = g_users[j + 1];
            }
            g_user_count--;
            
            // Also revoke all tokens for this user
            webdav_push_token_revoke_all(username);
            
            return true;
        }
    }
    
    return false;
}

bool webdav_push_user_update_password(const char* username, const char* new_password) {
    if (!g_auth_initialized || !username || !new_password) {
        return false;
    }
    
    WebDAVPushUser* user = webdav_push_user_get(username);
    if (!user) {
        return false;
    }
    
    // Hash new password
    webdav_push_password_hash(new_password, user->password_hash);
    
    return true;
}

bool webdav_push_user_update_permissions(const char* username, WebDAVPushPermission permissions) {
    if (!g_auth_initialized || !username) {
        return false;
    }
    
    WebDAVPushUser* user = webdav_push_user_get(username);
    if (!user) {
        return false;
    }
    
    user->permissions = permissions;
    return true;
}

bool webdav_push_user_set_enabled(const char* username, bool enabled) {
    if (!g_auth_initialized || !username) {
        return false;
    }
    
    WebDAVPushUser* user = webdav_push_user_get(username);
    if (!user) {
        return false;
    }
    
    user->enabled = enabled;
    return true;
}

WebDAVPushUser* webdav_push_user_get(const char* username) {
    if (!g_auth_initialized || !username) {
        return NULL;
    }
    
    for (int i = 0; i < g_user_count; i++) {
        if (strcmp(g_users[i].username, username) == 0 && g_users[i].enabled) {
            return &g_users[i];
        }
    }
    
    return NULL;
}

WebDAVPushUser* webdav_push_user_get_by_client(uint32_t client_id) {
    if (!g_auth_initialized) {
        return NULL;
    }
    
    // Find session for client
    for (int i = 0; i < g_session_count; i++) {
        if (g_sessions[i].client_id == client_id && g_sessions[i].authenticated) {
            return webdav_push_user_get(g_sessions[i].username);
        }
    }
    
    return NULL;
}

// ============================================================================
// PASSWORD HASHING
// ============================================================================

// Simple hash function for embedded systems
// In production, use a proper cryptographic hash like SHA-256

/// @brief Simple hash function (not cryptographically secure, but sufficient for embedded)
/// @param password Password to hash
/// @param hash Output buffer
static void simple_hash(const char* password, char* hash) {
    if (!password || !hash) return;
    
    uint8_t hash_bytes[32] = {0};
    
    for (int i = 0; password[i] != '\0' && i < 256; i++) {
        uint8_t c = password[i];
        for (int j = 0; j < 32; j++) {
            hash_bytes[j] = (hash_bytes[j] << 5) + hash_bytes[j] + c;
            hash_bytes[j] ^= (hash_bytes[j] >> 3);
        }
    }
    
    // Convert to hex
    for (int i = 0; i < 16; i++) {
        sprintf(hash + i * 2, "%02x", hash_bytes[i]);
    }
    hash[32] = '\0';
}

void webdav_push_password_hash(const char* password, char* hash) {
    if (!password || !hash) return;
    
    // Use simple hash for demo
    // In production: use SHA-256 or similar
    simple_hash(password, hash);
}

bool webdav_push_password_verify(const char* password, const char* hash) {
    if (!password || !hash) return false;
    
    char computed_hash[WEBDAV_PUSH_MAX_PASSWORD];
    webdav_push_password_hash(password, computed_hash);
    
    return strcmp(computed_hash, hash) == 0;
}

// ============================================================================
// SESSION MANAGEMENT
// ============================================================================

const char* webdav_push_session_create(const char* username, WebDAVPushPermission permissions) {
    if (!g_auth_initialized || !username) {
        return NULL;
    }
    
    // Check if user exists
    WebDAVPushUser* user = webdav_push_user_get(username);
    if (!user) {
        return NULL;
    }
    
    // Find free session slot
    for (int i = 0; i < WEBDAV_PUSH_MAX_SESSIONS; i++) {
        if (g_sessions[i].session_id[0] == '\0') {
            // Generate session ID
            const char* session_id = webdav_push_create_session_id();
            if (!session_id) {
                return NULL;
            }
            
            strncpy(g_sessions[i].session_id, session_id, sizeof(g_sessions[i].session_id) - 1);
            g_sessions[i].session_id[sizeof(g_sessions[i].session_id) - 1] = '\0';
            
            strncpy(g_sessions[i].username, username, sizeof(g_sessions[i].username) - 1);
            g_sessions[i].username[sizeof(g_sessions[i].username) - 1] = '\0';
            
            g_sessions[i].client_id = 0;  // Will be set when client connects
            g_sessions[i].created_at = get_system_time();
            g_sessions[i].last_activity = g_sessions[i].created_at;
            g_sessions[i].permissions = permissions;
            g_sessions[i].authenticated = true;
            
            g_session_count++;
            
            return g_sessions[i].session_id;
        }
    }
    
    return NULL;  // No free slots
}

WebDAVPushSession* webdav_push_session_get(const char* session_id) {
    if (!g_auth_initialized || !session_id) {
        return NULL;
    }
    
    for (int i = 0; i < g_session_count; i++) {
        if (strcmp(g_sessions[i].session_id, session_id) == 0 && g_sessions[i].authenticated) {
            return &g_sessions[i];
        }
    }
    
    return NULL;
}

WebDAVPushSession* webdav_push_session_get_by_client(uint32_t client_id) {
    if (!g_auth_initialized) {
        return NULL;
    }
    
    for (int i = 0; i < g_session_count; i++) {
        if (g_sessions[i].client_id == client_id && g_sessions[i].authenticated) {
            return &g_sessions[i];
        }
    }
    
    return NULL;
}

bool webdav_push_session_destroy(const char* session_id) {
    if (!g_auth_initialized || !session_id) {
        return false;
    }
    
    for (int i = 0; i < g_session_count; i++) {
        if (strcmp(g_sessions[i].session_id, session_id) == 0) {
            // Clear session
            memset(g_sessions[i].session_id, 0, sizeof(g_sessions[i].session_id));
            g_sessions[i].username[0] = '\0';
            g_sessions[i].client_id = 0;
            g_sessions[i].authenticated = false;
            
            return true;
        }
    }
    
    return false;
}

bool webdav_push_session_destroy_by_client(uint32_t client_id) {
    if (!g_auth_initialized) {
        return false;
    }
    
    for (int i = 0; i < g_session_count; i++) {
        if (g_sessions[i].client_id == client_id) {
            return webdav_push_session_destroy(g_sessions[i].session_id);
        }
    }
    
    return false;
}

void webdav_push_session_ping(const char* session_id) {
    if (!g_auth_initialized || !session_id) {
        return;
    }
    
    WebDAVPushSession* session = webdav_push_session_get(session_id);
    if (session) {
        session->last_activity = get_system_time();
    }
}

void webdav_push_session_cleanup(void) {
    if (!g_auth_initialized) {
        return;
    }
    
    uint64_t now = get_system_time();
    
    for (int i = 0; i < g_session_count; i++) {
        if (g_sessions[i].authenticated && 
            now - g_sessions[i].last_activity > WEBDAV_PUSH_SESSION_TIMEOUT) {
            // Session expired
            memset(g_sessions[i].session_id, 0, sizeof(g_sessions[i].session_id));
            g_sessions[i].authenticated = false;
        }
    }
}

const char* webdav_push_session_generate_id(void) {
    static char session_id[WEBDAV_PUSH_MAX_SESSION_ID + 1];
    webdav_push_generate_random_string(session_id, WEBDAV_PUSH_MAX_SESSION_ID);
    session_id[WEBDAV_PUSH_MAX_SESSION_ID] = '\0';
    return session_id;
}

// ============================================================================
// AUTHENTICATION
// ============================================================================

bool webdav_push_auth_login(uint32_t client_id, const char* username, const char* password) {
    if (!g_auth_initialized || !username || !password) {
        return false;
    }
    
    // Check if authentication is required
    if (!g_auth_config.require_auth && g_auth_config.allow_anonymous) {
        // Anonymous access allowed
        WebDAVPushAuthState* auth = &g_auth_states[client_id % WEBDAV_PUSH_MAX_CLIENTS];
        auth->authenticated = true;
        auth->auth_method = WEBDAV_PUSH_AUTH_ANONYMOUS;
        auth->username[0] = '\0';
        auth->permissions = WEBDAV_PUSH_PERM_READ;  // Read-only for anonymous
        auth->failed_attempts = 0;
        return true;
    }
    
    // Check rate limiting for auth attempts
    WebDAVPushAuthState* auth = &g_auth_states[client_id % WEBDAV_PUSH_MAX_CLIENTS];
    
    // Check lockout
    uint64_t now = get_system_time();
    if (auth->failed_attempts >= WEBDAV_PUSH_MAX_FAILED_ATTEMPTS &&
        now - auth->last_auth_attempt < WEBDAV_PUSH_LOCKOUT_DURATION) {
        return false;  // Locked out
    }
    
    // Verify credentials
    WebDAVPushUser* user = webdav_push_user_get(username);
    if (!user || !webdav_push_password_verify(password, user->password_hash)) {
        auth->failed_attempts++;
        auth->last_auth_attempt = now;
        return false;
    }
    
    // Authentication successful
    auth->authenticated = true;
    auth->auth_method = WEBDAV_PUSH_AUTH_BASIC;
    strncpy(auth->username, username, sizeof(auth->username) - 1);
    auth->username[sizeof(auth->username) - 1] = '\0';
    auth->permissions = user->permissions;
    auth->failed_attempts = 0;
    
    // Create session if using session tokens
    if (g_auth_config.use_session_tokens) {
        webdav_push_session_create(username, user->permissions);
    }
    
    return true;
}

bool webdav_push_auth_token(uint32_t client_id, const char* token) {
    if (!g_auth_initialized || !token) {
        return false;
    }
    
    // Check if authentication is required
    if (!g_auth_config.require_auth && g_auth_config.allow_anonymous) {
        // Anonymous access allowed
        WebDAVPushAuthState* auth = &g_auth_states[client_id % WEBDAV_PUSH_MAX_CLIENTS];
        auth->authenticated = true;
        auth->auth_method = WEBDAV_PUSH_AUTH_ANONYMOUS;
        auth->permissions = WEBDAV_PUSH_PERM_READ;
        return true;
    }
    
    // Validate token
    WebDAVPushToken* tok = webdav_push_token_get(token);
    if (!tok || !tok->used) {
        return false;
    }
    
    // Check expiry
    if (tok->expires_at != 0 && get_system_time() > tok->expires_at) {
        return false;
    }
    
    // Token is valid
    WebDAVPushAuthState* auth = &g_auth_states[client_id % WEBDAV_PUSH_MAX_CLIENTS];
    auth->authenticated = true;
    auth->auth_method = WEBDAV_PUSH_AUTH_TOKEN;
    strncpy(auth->username, tok->username, sizeof(auth->username) - 1);
    auth->username[sizeof(auth->username) - 1] = '\0';
    auth->permissions = tok->permissions;
    auth->failed_attempts = 0;
    
    // Associate token with session
    WebDAVPushSession* session = webdav_push_session_get_by_client(client_id);
    if (session) {
        // Already has session
    } else {
        // Create new session
        const char* session_id = webdav_push_session_create(tok->username, tok->permissions);
        if (session_id) {
            strncpy(auth->session_id, session_id, sizeof(auth->session_id) - 1);
            auth->session_id[sizeof(auth->session_id) - 1] = '\0';
        }
    }
    
    return true;
}

bool webdav_push_auth_logout(uint32_t client_id) {
    if (!g_auth_initialized) {
        return false;
    }
    
    WebDAVPushAuthState* auth = &g_auth_states[client_id % WEBDAV_PUSH_MAX_CLIENTS];
    if (!auth->authenticated) {
        return false;
    }
    
    // Destroy session
    webdav_push_session_destroy_by_client(client_id);
    
    // Clear auth state
    auth->authenticated = false;
    auth->username[0] = '\0';
    auth->session_id[0] = '\0';
    auth->permissions = 0;
    auth->failed_attempts = 0;
    
    return true;
}

bool webdav_push_auth_is_authenticated(uint32_t client_id) {
    if (!g_auth_initialized) {
        return g_auth_config.allow_anonymous;
    }
    
    // Check session first
    WebDAVPushSession* session = webdav_push_session_get_by_client(client_id);
    if (session && session->authenticated) {
        return true;
    }
    
    // Check auth state
    WebDAVPushAuthState* auth = &g_auth_states[client_id % WEBDAV_PUSH_MAX_CLIENTS];
    return auth->authenticated;
}

WebDAVPushAuthState* webdav_push_auth_get_state(uint32_t client_id) {
    if (!g_auth_initialized) {
        return NULL;
    }
    
    return &g_auth_states[client_id % WEBDAV_PUSH_MAX_CLIENTS];
}

bool webdav_push_auth_has_permission(uint32_t client_id, WebDAVPushPermission permission) {
    if (!g_auth_initialized) {
        return false;
    }
    
    // Check session
    WebDAVPushSession* session = webdav_push_session_get_by_client(client_id);
    if (session && session->authenticated) {
        return (session->permissions & permission) == permission;
    }
    
    // Check auth state
    WebDAVPushAuthState* auth = &g_auth_states[client_id % WEBDAV_PUSH_MAX_CLIENTS];
    if (auth->authenticated) {
        return (auth->permissions & permission) == permission;
    }
    
    return false;
}

// ============================================================================
// TOKEN MANAGEMENT
// ============================================================================

const char* webdav_push_token_generate(const char* username, WebDAVPushPermission permissions, uint32_t expiry) {
    if (!g_auth_initialized || !username) {
        return NULL;
    }
    
    // Check if user exists
    WebDAVPushUser* user = webdav_push_user_get(username);
    if (!user) {
        return NULL;
    }
    
    // Check token expiry
    if (g_auth_config.token_expiry > 0 && expiry > g_auth_config.token_expiry) {
        expiry = g_auth_config.token_expiry;
    }
    
    // Find free token slot
    for (int i = 0; i < WEBDAV_PUSH_MAX_TOKENS; i++) {
        if (g_tokens[i].token[0] == '\0' || !g_tokens[i].used) {
            // Generate token
            const char* token = webdav_push_create_token();
            if (!token) {
                return NULL;
            }
            
            strncpy(g_tokens[i].token, token, sizeof(g_tokens[i].token) - 1);
            g_tokens[i].token[sizeof(g_tokens[i].token) - 1] = '\0';
            
            strncpy(g_tokens[i].username, username, sizeof(g_tokens[i].username) - 1);
            g_tokens[i].username[sizeof(g_tokens[i].username) - 1] = '\0';
            
            g_tokens[i].permissions = permissions;
            g_tokens[i].created_at = get_system_time();
            g_tokens[i].expires_at = (expiry > 0) ? g_tokens[i].created_at + expiry : 0;
            g_tokens[i].used = true;
            
            g_token_count++;
            
            return g_tokens[i].token;
        }
    }
    
    return NULL;  // No free slots
}

bool webdav_push_token_validate(const char* token) {
    if (!g_auth_initialized || !token) {
        return false;
    }
    
    for (int i = 0; i < g_token_count; i++) {
        if (g_tokens[i].used && strcmp(g_tokens[i].token, token) == 0) {
            // Check expiry
            if (g_tokens[i].expires_at != 0 && get_system_time() > g_tokens[i].expires_at) {
                // Token expired
                g_tokens[i].used = false;
                return false;
            }
            return true;
        }
    }
    
    return false;
}

WebDAVPushToken* webdav_push_token_get(const char* token) {
    if (!g_auth_initialized || !token) {
        return NULL;
    }
    
    for (int i = 0; i < g_token_count; i++) {
        if (g_tokens[i].used && strcmp(g_tokens[i].token, token) == 0) {
            // Check expiry
            if (g_tokens[i].expires_at != 0 && get_system_time() > g_tokens[i].expires_at) {
                g_tokens[i].used = false;
                return NULL;
            }
            return &g_tokens[i];
        }
    }
    
    return NULL;
}

bool webdav_push_token_revoke(const char* token) {
    if (!g_auth_initialized || !token) {
        return false;
    }
    
    for (int i = 0; i < g_token_count; i++) {
        if (g_tokens[i].used && strcmp(g_tokens[i].token, token) == 0) {
            // Clear token
            memset(g_tokens[i].token, 0, sizeof(g_tokens[i].token));
            g_tokens[i].used = false;
            return true;
        }
    }
    
    return false;
}

int webdav_push_token_revoke_all(const char* username) {
    if (!g_auth_initialized || !username) {
        return 0;
    }
    
    int count = 0;
    for (int i = 0; i < g_token_count; i++) {
        if (g_tokens[i].used && strcmp(g_tokens[i].username, username) == 0) {
            memset(g_tokens[i].token, 0, sizeof(g_tokens[i].token));
            g_tokens[i].used = false;
            count++;
        }
    }
    
    return count;
}

WebDAVPushToken** webdav_push_token_list(void) {
    static WebDAVPushToken* tokens[WEBDAV_PUSH_MAX_TOKENS];
    int count = 0;
    
    if (!g_auth_initialized) {
        tokens[0] = NULL;
        return tokens;
    }
    
    for (int i = 0; i < g_token_count; i++) {
        if (g_tokens[i].used) {
            tokens[count++] = &g_tokens[i];
        }
    }
    tokens[count] = NULL;
    
    return tokens;
}

void webdav_push_token_cleanup(void) {
    if (!g_auth_initialized) {
        return;
    }
    
    uint64_t now = get_system_time();
    
    for (int i = 0; i < g_token_count; i++) {
        if (g_tokens[i].used && g_tokens[i].expires_at != 0 && now > g_tokens[i].expires_at) {
            memset(g_tokens[i].token, 0, sizeof(g_tokens[i].token));
            g_tokens[i].used = false;
        }
    }
}

// ============================================================================
// RATE LIMITING
// ============================================================================

bool webdav_push_rate_limit_check(uint32_t client_id) {
    if (!g_auth_initialized) {
        return false;
    }
    
    uint64_t now = get_system_time();
    int idx = client_id % WEBDAV_PUSH_MAX_CLIENTS;
    
    // Reset count if more than 1 minute has passed
    if (now - g_notification_timestamps[idx] > 60000) {
        g_notification_counts[idx] = 0;
        g_notification_timestamps[idx] = now;
    }
    
    // Check limit (default: 60 per minute)
    uint32_t limit = 60;
    return g_notification_counts[idx] >= limit;
}

void webdav_push_rate_limit_record(uint32_t client_id) {
    if (!g_auth_initialized) {
        return;
    }
    
    int idx = client_id % WEBDAV_PUSH_MAX_CLIENTS;
    
    uint64_t now = get_system_time();
    if (now - g_notification_timestamps[idx] > 60000) {
        g_notification_counts[idx] = 0;
        g_notification_timestamps[idx] = now;
    }
    
    g_notification_counts[idx]++;
}

uint32_t webdav_push_rate_limit_remaining(uint32_t client_id) {
    if (!g_auth_initialized) {
        return 0;
    }
    
    int idx = client_id % WEBDAV_PUSH_MAX_CLIENTS;
    uint64_t now = get_system_time();
    
    if (now - g_notification_timestamps[idx] > 60000) {
        return 60;  // Full limit available
    }
    
    uint32_t limit = 60;
    if (g_notification_counts[idx] >= limit) {
        return 0;
    }
    return limit - g_notification_counts[idx];
}

// ============================================================================
// SECURITY UTILITIES
// ============================================================================

// Simple pseudo-random number generator (for embedded systems)
static uint32_t g_random_seed = 1;

static uint32_t pseudo_random(void) {
    g_random_seed = (g_random_seed * 1103515245 + 12345) & 0x7FFFFFFF;
    return g_random_seed;
}

static void seed_random(uint32_t seed) {
    if (seed != 0) {
        g_random_seed = seed;
    }
    // Seed from system time if available
    g_random_seed = get_system_time();
}

void webdav_push_generate_random_string(char* output, size_t length) {
    if (!output || length == 0) {
        return;
    }
    
    static bool seeded = false;
    if (!seeded) {
        seed_random(get_system_time());
        seeded = true;
    }
    
    const char charset[] = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
    const size_t charset_size = sizeof(charset) - 1;
    
    for (size_t i = 0; i < length; i++) {
        output[i] = charset[pseudo_random() % charset_size];
    }
    output[length] = '\0';
}

const char* webdav_push_create_session_id(void) {
    static char session_id[WEBDAV_PUSH_MAX_SESSION_ID + 1];
    webdav_push_generate_random_string(session_id, WEBDAV_PUSH_MAX_SESSION_ID);
    return session_id;
}

const char* webdav_push_create_token(void) {
    static char token[WEBDAV_PUSH_MAX_TOKEN + 1];
    webdav_push_generate_random_string(token, WEBDAV_PUSH_MAX_TOKEN);
    return token;
}

// ============================================================================
// INTERNAL: TIME FUNCTION
// ============================================================================

/// @brief Get current system time in milliseconds
static uint64_t get_system_time(void) {
    // In real implementation, use platform-specific timer
    // For demo, return a mock value
    static uint64_t mock_time = 0;
    return mock_time += 100;
}
