/**
 * GUIKit Hardware Configuration - Unified Struct for ESP8266 and ESP32
 * 
 * Single common configuration structure for both microcontrollers
 * Simple, clean design matching the user's requested format
 * 
 * User concept: struct config = {
 *   ram: { internal: bool, bank: {} },
 *   spi: { expander: bool, bank: {} }
 * }
 * 
 * Generated by Mistral Vibe
 * Date: 2026-08-15
 */

#ifndef GUIKIT_HW_CONFIG_H
#define GUIKIT_HW_CONFIG_H

#include <stdint.h>
#include <stdbool.h>

// ============================================================================
// Platform Detection
// ============================================================================

#if defined(ESP8266)
    #define GUIKIT_PLATFORM_ESP8266 1
    #define GUIKIT_PLATFORM_ESP32   0
#elif defined(ESP32)
    #define GUIKIT_PLATFORM_ESP8266 0
    #define GUIKIT_PLATFORM_ESP32   1
#else
    #define GUIKIT_PLATFORM_ESP8266 0
    #define GUIKIT_PLATFORM_ESP32   0
#endif

// ============================================================================
// Simple RAM Bank Structure
// ============================================================================

typedef enum {
    GUIKIT_RAM_NONE = 0,
    GUIKIT_RAM_INTERNAL,
    GUIKIT_RAM_SRAM,      // SPI SRAM (23LC series)
    GUIKIT_RAM_PSRAM,     // ESP32 PSRAM
    GUIKIT_RAM_FRAM       // Non-volatile FRAM
} guikit_ram_type_t;

// Single RAM bank entry
typedef struct {
    guikit_ram_type_t type;
    uint32_t size;         // Size in bytes
    uint8_t cs_pin;        // CS pin (255 = not applicable for internal)
    bool enabled;
} guikit_ram_bank_t;

// RAM Configuration (matches user concept: ram:{internal:bool, bank:{}})
typedef struct {
    bool internal;         // Internal RAM available
    guikit_ram_bank_t bank[8];  // External RAM banks
    uint8_t bank_count;
} guikit_ram_config_t;

// ============================================================================
// Simple SPI Device/Expander Structure
// ============================================================================

typedef enum {
    GUIKIT_SPI_NONE = 0,
    GUIKIT_SPI_DEVICE,    // Generic SPI device (TFT, SD, etc.)
    GUIKIT_SPI_EXPANDER   // GPIO expander (MCP23S17, etc.)
} guikit_spi_type_t;

typedef enum {
    GUIKIT_EXPANDER_NONE = 0,
    GUIKIT_EXPANDER_MCP23S17,
    GUIKIT_EXPANDER_MCP23S08,
    GUIKIT_EXPANDER_MCP23017,
    GUIKIT_EXPANDER_MCP23008
} guikit_expander_type_t;

// SPI Device Type Enumeration
typedef enum {
    GUIKIT_SPI_DEVICE_NONE = 0,
    GUIKIT_SPI_DEVICE_SRAM,        // SPI SRAM (23LC1024, etc.)
    GUIKIT_SPI_DEVICE_PSRAM,       // PSRAM
    GUIKIT_SPI_DEVICE_SD_CARD,     // SD Card
    GUIKIT_SPI_DEVICE_TFT,        // TFT Display
    GUIKIT_SPI_DEVICE_TOUCH,      // Touch Controller
    GUIKIT_SPI_DEVICE_EXPANDER,   // GPIO Expander
    GUIKIT_SPI_DEVICE_FRAM,       // FRAM
    GUIKIT_SPI_DEVICE_EEPROM,      // SPI EEPROM
    GUIKIT_SPI_DEVICE_FLASH,       // SPI Flash
    GUIKIT_SPI_DEVICE_UNKNOWN     // Unknown device
} guikit_spi_device_type_t;

// Single SPI device/expander entry
typedef struct {
    guikit_spi_type_t type;
    guikit_expander_type_t expander_type;  // If type == SPI_EXPANDER
    uint8_t cs_pin;        // Chip select pin
    uint8_t irq_pin;       // IRQ pin (255 = not used)
    bool enabled;
} guikit_spi_bank_t;

// SPI Configuration (matches user concept: spi:{expander:bool, bank:{}})
typedef struct {
    bool expander;        // SPI expander enabled
    guikit_spi_bank_t bank[8];   // SPI devices/expanders
    uint8_t bank_count;
    
    // SPI bus settings
    uint8_t sck_pin;
    uint8_t mosi_pin;
    uint8_t miso_pin;
    uint8_t max_speed_mhz;  // Max SPI speed in MHz
} guikit_spi_config_t;

// ============================================================================
// Display Configuration (added for completeness)
// ============================================================================

typedef struct {
    uint16_t width;
    uint16_t height;
    uint8_t color_depth;  // 1, 2, 4, 8, 16, 24 bpp
    bool double_buffer;
} guikit_display_config_t;

// ============================================================================
// Memory Strategy Configuration
// Hierarchical strategy: External RAM -> SD Card Swap -> Internal RAM
// ============================================================================

typedef enum {
    MEMORY_STRATEGY_EXTERNAL_RAM = 0,  // Use external SRAM (preferred)
    MEMORY_STRATEGY_SD_SWAP,          // Use SD card as swap/streaming storage
    MEMORY_STRATEGY_INTERNAL_RAM,    // Use internal RAM (fallback)
    MEMORY_STRATEGY_FAILED            // All strategies failed
} MemoryStrategyLevel;

/**
 * Memory strategy configuration struct
 * Controls thresholds and behavior for hierarchical memory management
 */
typedef struct {
    // Thresholds for strategy selection
    uint32_t external_ram_min_size;    // Min GUI size to use external RAM (default: 4096)
    uint32_t sd_swap_min_size;        // Min GUI size to use SD swap (default: 16384)
    uint32_t internal_ram_max_size;   // Max GUI size for internal RAM (default: 8192)
    
    // External RAM limits
    uint32_t external_ram_max_size;   // Max size for external RAM storage (default: 131072 = 128KB)
    uint32_t external_ram_base_addr;   // Base address in external RAM (default: 0)
    
    // SD Card swap configuration
    uint16_t sd_swap_block_size;      // SD card sector size (default: 512)
    uint16_t sd_swap_cache_size;      // Cache size for streaming (default: 2048)
    
    // Strategy behavior flags
    bool use_external_ram_by_default; // Try external RAM first if available
    bool use_sd_swap_by_default;     // Try SD swap if external RAM unavailable
    bool check_memory_before_load;   // Validate memory before loading
    bool display_error_on_tft;       // Display errors on TFT screen
    
    // Current/active settings (runtime)
    MemoryStrategyLevel current_strategy;
    bool strategy_initialized;
    
} memory_strategy_config_t;

// ============================================================================
// THE Single Common Config Struct for Both MCUs
// ============================================================================

/**
 * Unified GUIKit Hardware Configuration
 * 
 * This single struct works for both ESP8266 and ESP32.
 * It matches the user's requested format:
 *   config = {
 *     ram: { internal: bool, bank: {} },
 *     spi: { expander: bool, bank: {} }
 *   }
 */
typedef struct {
    // Platform info
    bool is_esp8266;
    bool is_esp32;
    
    // SMP (Symmetric Multi-Processing) info - detected at runtime
    bool smp_available;        // true if multiple cores are available
    uint8_t cpu_core_count;    // Number of available CPU cores (1 or 2)
    uint8_t current_cpu_core;   // Current core ID (0 = PRO_CPU, 1 = APP_CPU on ESP32)
    
    // RAM configuration (user concept: ram:{internal:bool, bank:{}})
    guikit_ram_config_t ram;
    
    // SPI configuration (user concept: spi:{expander:bool, bank:{}})
    guikit_spi_config_t spi;
    
    // Display configuration
    guikit_display_config_t display;
    
    // Memory strategy configuration
    memory_strategy_config_t memory_strategy;
    
    // System flags
    bool use_sd_card;
    bool use_webdav;
    bool debug_mode;
    
} guikit_hw_config_t;

// ============================================================================
// Default Configurations
// ============================================================================

// Default for both platforms
extern const guikit_hw_config_t GUIKIT_HW_DEFAULT;

// ESP8266 specific defaults
extern const guikit_hw_config_t GUIKIT_HW_ESP8266_DEFAULT;

// ESP32 specific defaults  
extern const guikit_hw_config_t GUIKIT_HW_ESP32_DEFAULT;

// ============================================================================
// Helper Macros
// ============================================================================

// Check current platform
#define GUIKIT_IS_ESP8266() (GUIKIT_PLATFORM_ESP8266)
#define GUIKIT_IS_ESP32()   (GUIKIT_PLATFORM_ESP32)

// RAM helpers
#define GUIKIT_HAS_INTERNAL_RAM(cfg) ((cfg).ram.internal)
#define GUIKIT_RAM_BANK_COUNT(cfg)   ((cfg).ram.bank_count)

// SPI helpers
#define GUIKIT_HAS_SPI_EXPANDER(cfg) ((cfg).spi.expander)
#define GUIKIT_SPI_BANK_COUNT(cfg)   ((cfg).spi.bank_count)

// Display helpers
#define GUIKIT_DISPLAY_WIDTH(cfg)    ((cfg).display.width)
#define GUIKIT_DISPLAY_HEIGHT(cfg)   ((cfg).display.height)
#define GUIKIT_DISPLAY_BPP(cfg)       ((cfg).display.color_depth)
#define GUIKIT_FRAMEBUFFER_SIZE(cfg) \
    ((cfg).display.width * (cfg).display.height * ((cfg).display.color_depth + 7) / 8)

// ============================================================================
// Memory Strategy Defaults
// ============================================================================

// Default memory strategy configuration
#define GUIKIT_MEMORY_STRATEGY_DEFAULT \
{ \
    .external_ram_min_size = 4096,           // 4KB minimum for external RAM \
    .sd_swap_min_size = 16384,              // 16KB minimum for SD swap \
    .internal_ram_max_size = 8192,          // 8KB maximum for internal RAM \
    .external_ram_max_size = 131072,        // 128KB for 23LC1024 \
    .external_ram_base_addr = 0,             // Start at beginning of SRAM \
    .sd_swap_block_size = 512,             // SD card sector size \
    .sd_swap_cache_size = 2048,            // 2KB cache for streaming \
    .use_external_ram_by_default = true,   // Try external RAM first \
    .use_sd_swap_by_default = true,        // Try SD swap if external unavailable \
    .check_memory_before_load = true,      // Validate memory before loading \
    .display_error_on_tft = true,          // Display errors on TFT \
    .current_strategy = MEMORY_STRATEGY_INTERNAL_RAM, \
    .strategy_initialized = false \
}

// ============================================================================
// Configuration Presets
// ============================================================================

// ESP8266 with 1MB SRAM (8x 23LC1024) - for Huge Demo
#define GUIKIT_HW_ESP8266_HUGE_DEMO \
{ \
    .is_esp8266 = true, \
    .is_esp32 = false, \
    .ram = { \
        .internal = true, \
        .bank_count = 8, \
        .bank = { \
            {GUIKIT_RAM_SRAM, 131072, 16, true},  // Bank 0 on D0
            {GUIKIT_RAM_SRAM, 131072, 0, true},   // Bank 1
            {GUIKIT_RAM_SRAM, 131072, 1, true},   // Bank 2
            {GUIKIT_RAM_SRAM, 131072, 2, true},   // Bank 3
            {GUIKIT_RAM_SRAM, 131072, 3, true},   // Bank 4
            {GUIKIT_RAM_SRAM, 131072, 4, true},   // Bank 5
            {GUIKIT_RAM_SRAM, 131072, 5, true},   // Bank 6
            {GUIKIT_RAM_SRAM, 131072, 6, true}    // Bank 7
        } \
    }, \
    .spi = { \
        .expander = false, \
        .bank_count = 4, \
        .bank = { \
            {GUIKIT_SPI_DEVICE, GUIKIT_EXPANDER_NONE, 15, 255, true},  // TFT on D8
            {GUIKIT_SPI_DEVICE, GUIKIT_EXPANDER_NONE, 4, 255, true},   // Touch on D2
            {GUIKIT_SPI_DEVICE, GUIKIT_EXPANDER_NONE, 5, 255, true},   // SD on D1
            {GUIKIT_SPI_DEVICE, GUIKIT_EXPANDER_NONE, 16, 255, true}   // SRAM on D0
        }, \
        .sck_pin = 14,   // D5
        .mosi_pin = 13,  // D7
        .miso_pin = 12,  // D6
        .max_speed_mhz = 20 \
    }, \
    .display = {320, 240, 4, true},  // 4bpp, double buffer
    .use_sd_card = true,
    .use_webdav = true,
    .debug_mode = false
}

// ESP8266 with 2x MCP23S17 Expanders
#define GUIKIT_HW_ESP8266_EXPANDER \
{ \
    .is_esp8266 = true, \
    .is_esp32 = false, \
    .ram = { \
        .internal = true, \
        .bank_count = 0 \
    }, \
    .spi = { \
        .expander = true, \
        .bank_count = 5, \
        .bank = { \
            {GUIKIT_SPI_DEVICE, GUIKIT_EXPANDER_NONE, 15, 255, true},   // TFT
            {GUIKIT_SPI_DEVICE, GUIKIT_EXPANDER_NONE, 4, 255, true},    // Touch
            {GUIKIT_SPI_DEVICE, GUIKIT_EXPANDER_NONE, 5, 255, true},    // SD
            {GUIKIT_SPI_EXPANDER, GUIKIT_EXPANDER_MCP23S17, 0, 255, true}, // Exp1 on D3
            {GUIKIT_SPI_EXPANDER, GUIKIT_EXPANDER_MCP23S17, 1, 255, true}  // Exp2 on D6
        }, \
        .sck_pin = 14, \
        .mosi_pin = 13, \
        .miso_pin = 12, \
        .max_speed_mhz = 20 \
    }, \
    .display = {320, 240, 4, false},
    .use_sd_card = true,
    .use_webdav = true,
    .debug_mode = false
}

// ESP32 Premium with 8MB PSRAM + 2x MCP23S17
#define GUIKIT_HW_ESP32_PREMIUM \
{ \
    .is_esp8266 = false, \
    .is_esp32 = true, \
    .ram = { \
        .internal = true, \
        .bank_count = 1, \
        .bank = { \
            {GUIKIT_RAM_PSRAM, 8 * 1024 * 1024, 255, true}  // 8MB PSRAM
        } \
    }, \
    .spi = { \
        .expander = true, \
        .bank_count = 5, \
        .bank = { \
            {GUIKIT_SPI_DEVICE, GUIKIT_EXPANDER_NONE, 5, 255, true},    // Device 1
            {GUIKIT_SPI_DEVICE, GUIKIT_EXPANDER_NONE, 21, 255, true},   // Device 2
            {GUIKIT_SPI_DEVICE, GUIKIT_EXPANDER_NONE, 22, 255, true},   // Device 3
            {GUIKIT_SPI_EXPANDER, GUIKIT_EXPANDER_MCP23S17, 16, 255, true}, // Exp1
            {GUIKIT_SPI_EXPANDER, GUIKIT_EXPANDER_MCP23S17, 17, 255, true}  // Exp2
        }, \
        .sck_pin = 18, \
        .mosi_pin = 23, \
        .miso_pin = 19, \
        .max_speed_mhz = 40 \
    }, \
    .display = {320, 240, 16, true},  // 16bpp, double buffer
    .use_sd_card = true,
    .use_webdav = true,
    .debug_mode = false
}

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Initialize config with platform defaults
 */
void guikit_hw_config_init(guikit_hw_config_t* cfg);

/**
 * Get total external RAM size
 */
uint32_t guikit_hw_get_external_ram(const guikit_hw_config_t* cfg);

/**
 * Get total RAM (internal + external)
 */
uint32_t guikit_hw_get_total_ram(const guikit_hw_config_t* cfg);

/**
 * Count number of SPI expander chips
 */
uint8_t guikit_hw_count_expanders(const guikit_hw_config_t* cfg);

/**
 * Get total GPIO from expanders
 */
uint16_t guikit_hw_get_expander_gpio(const guikit_hw_config_t* cfg);

/**
 * Validate configuration
 */
bool guikit_hw_config_validate(const guikit_hw_config_t* cfg);

/**
 * Print configuration summary
 */
void guikit_hw_config_print(const guikit_hw_config_t* cfg);

// ============================================================================
// Memory Strategy Configuration Helpers
// ============================================================================

/**
 * Initialize memory strategy config with defaults
 */
void guikit_memory_strategy_config_init(memory_strategy_config_t* cfg);

/**
 * Validate memory strategy configuration
 */
bool guikit_memory_strategy_config_validate(const memory_strategy_config_t* cfg);

/**
 * Check if memory strategy should use external RAM for given GUI size
 */
bool guikit_memory_strategy_should_use_external_ram(const memory_strategy_config_t* cfg, uint32_t gui_size);

/**
 * Check if memory strategy should use SD swap for given GUI size
 */
bool guikit_memory_strategy_should_use_sd_swap(const memory_strategy_config_t* cfg, uint32_t gui_size);

/**
 * Check if memory strategy should use internal RAM for given GUI size
 */
bool guikit_memory_strategy_should_use_internal_ram(const memory_strategy_config_t* cfg, uint32_t gui_size);

/**
 * Select memory strategy based on GUI size and configuration
 */
MemoryStrategyLevel guikit_memory_strategy_select(const memory_strategy_config_t* cfg, 
                                                    uint32_t gui_size, 
                                                    bool sram_available, 
                                                    bool sdcard_available);

#endif // GUIKIT_HW_CONFIG_H
