/**
 * GUIKit Hardware Configuration - Union-Based Version
 * 
 * Memory-efficient configuration using unions
 * Single struct for both ESP8266 and ESP32 with union-based bank storage
 * 
 * User concept: Use union for config struct
 * 
 * Generated by Mistral Vibe
 * Date: 2026-08-15
 */

#ifndef GUIKIT_HW_CONFIG_UNION_H
#define GUIKIT_HW_CONFIG_UNION_H

#include <stdint.h>
#include <stdbool.h>

// ============================================================================
// Platform Detection
// ============================================================================

#if defined(ESP8266)
    #define GUIKIT_PLATFORM_ESP8266 1
    #define GUIKIT_PLATFORM_ESP32   0
#elif defined(ESP32)
    #define GUIKIT_PLATFORM_ESP8266 0
    #define GUIKIT_PLATFORM_ESP32   1
#else
    #define GUIKIT_PLATFORM_ESP8266 0
    #define GUIKIT_PLATFORM_ESP32   0
#endif

// ============================================================================
// Device Types
// ============================================================================

typedef enum {
    GUIKIT_DEVICE_NONE = 0,
    GUIKIT_DEVICE_RAM_INTERNAL,
    GUIKIT_DEVICE_RAM_SRAM,
    GUIKIT_DEVICE_RAM_PSRAM,
    GUIKIT_DEVICE_RAM_FRAM,
    GUIKIT_DEVICE_SPI_GENERIC,
    GUIKIT_DEVICE_SPI_EXPANDER,
    GUIKIT_DEVICE_TFT,
    GUIKIT_DEVICE_TOUCH,
    GUIKIT_DEVICE_SD_CARD
} guikit_device_type_t;

// ============================================================================
// RAM Types (subset of device types for RAM-specific)
// ============================================================================

typedef enum {
    GUIKIT_RAM_NONE = 0,
    GUIKIT_RAM_INTERNAL,
    GUIKIT_RAM_SRAM,
    GUIKIT_RAM_PSRAM,
    GUIKIT_RAM_FRAM
} guikit_ram_type_t;

// ============================================================================
// Expander Types
// ============================================================================

typedef enum {
    GUIKIT_EXPANDER_NONE = 0,
    GUIKIT_EXPANDER_MCP23S17,
    GUIKIT_EXPANDER_MCP23S08,
    GUIKIT_EXPANDER_MCP23017,
    GUIKIT_EXPANDER_MCP23008
} guikit_expander_type_t;

// ============================================================================
// Union-Based Device Configuration
// Each device slot can be configured as any type of device
// ============================================================================

// RAM-specific configuration
typedef struct {
    guikit_ram_type_t type;
    uint32_t size;         // Size in bytes
    uint8_t cs_pin;        // CS pin (255 = not applicable)
} guikit_ram_config_t;

// SPI device-specific configuration
typedef struct {
    guikit_device_type_t type;
    uint8_t cs_pin;        // CS pin
    uint8_t irq_pin;       // IRQ pin (255 = not used)
    uint8_t speed_mhz;     // Device-specific speed
} guikit_spi_device_config_t;

// SPI expander-specific configuration
typedef struct {
    guikit_expander_type_t type;
    uint8_t cs_pin;        // CS pin
    uint8_t irq_pin;       // IRQ pin (255 = not used)
    uint8_t reset_pin;     // Reset pin (255 = not used)
} guikit_spi_expander_config_t;

// Display-specific configuration
typedef struct {
    uint16_t width;
    uint16_t height;
    uint8_t color_depth;  // 1, 2, 4, 8, 16, 24 bpp
    bool double_buffer;
} guikit_display_config_t;

// ============================================================================
// THE Union-Based Bank Structure
// Each bank can be either RAM, SPI device, or SPI expander
// ============================================================================

typedef struct {
    guikit_device_type_t device_type;  // What type of device this is
    bool enabled;
    
    // Union of all possible device configurations
    union {
        guikit_ram_config_t ram;
        guikit_spi_device_config_t spi_device;
        guikit_spi_expander_config_t spi_expander;
    } config;
    
    const char* name;  // Optional human-readable name
} guikit_device_bank_t;

// ============================================================================
// Main Configuration Struct with Union-Based Banks
// ============================================================================

/**
 * Unified GUIKit Hardware Configuration using Unions
 * 
 * Single struct for both ESP8266 and ESP32
 * Uses unions to allow each bank to be any type of device
 */
typedef struct {
    // Platform info
    bool is_esp8266;
    bool is_esp32;
    
    // Device banks - each can be RAM, SPI device, or SPI expander
    guikit_device_bank_t banks[16];  // Up to 16 devices total
    uint8_t bank_count;
    
    // SPI bus settings (shared across all SPI devices)
    uint8_t sck_pin;
    uint8_t mosi_pin;
    uint8_t miso_pin;
    uint8_t max_speed_mhz;  // Max SPI speed in MHz
    
    // Display configuration
    guikit_display_config_t display;
    
    // System flags
    bool use_sd_card;
    bool use_webdav;
    bool debug_mode;
    
} guikit_hw_config_union_t;

// ============================================================================
// Convenience Accessors
// ============================================================================

// Helper to access RAM config from a bank
#define GUIKIT_BANK_RAM(bank) ((bank).config.ram)

// Helper to access SPI device config from a bank
#define GUIKIT_BANK_SPI_DEVICE(bank) ((bank).config.spi_device)

// Helper to access SPI expander config from a bank
#define GUIKIT_BANK_SPI_EXPANDER(bank) ((bank).config.spi_expander)

// Check if bank is RAM
#define GUIKIT_BANK_IS_RAM(bank) \
    ((bank).device_type == GUIKIT_DEVICE_RAM_INTERNAL || \
     (bank).device_type == GUIKIT_DEVICE_RAM_SRAM || \
     (bank).device_type == GUIKIT_DEVICE_RAM_PSRAM || \
     (bank).device_type == GUIKIT_DEVICE_RAM_FRAM)

// Check if bank is SPI device
#define GUIKIT_BANK_IS_SPI_DEVICE(bank) \
    ((bank).device_type == GUIKIT_DEVICE_SPI_GENERIC || \
     (bank).device_type == GUIKIT_DEVICE_TFT || \
     (bank).device_type == GUIKIT_DEVICE_TOUCH || \
     (bank).device_type == GUIKIT_DEVICE_SD_CARD)

// Check if bank is SPI expander
#define GUIKIT_BANK_IS_SPI_EXPANDER(bank) \
    ((bank).device_type == GUIKIT_DEVICE_SPI_EXPANDER)

// ============================================================================
// Default Configurations
// ============================================================================

// Helper macro to create a RAM bank entry
#define GUIKIT_RAM_BANK(ram_type, size, cs_pin, name) \
{ \
    .device_type = (ram_type == GUIKIT_RAM_INTERNAL ? GUIKIT_DEVICE_RAM_INTERNAL : \
                   ram_type == GUIKIT_RAM_SRAM ? GUIKIT_DEVICE_RAM_SRAM : \
                   ram_type == GUIKIT_RAM_PSRAM ? GUIKIT_DEVICE_RAM_PSRAM : GUIKIT_DEVICE_RAM_FRAM), \
    .enabled = true, \
    .config.ram = {.type = ram_type, .size = size, .cs_pin = cs_pin}, \
    .name = name \
}

// Helper macro to create an SPI device bank entry
#define GUIKIT_SPI_DEVICE_BANK(device_type, cs_pin, irq_pin, speed, name) \
{ \
    .device_type = device_type, \
    .enabled = true, \
    .config.spi_device = {.type = device_type, .cs_pin = cs_pin, .irq_pin = irq_pin, .speed_mhz = speed}, \
    .name = name \
}

// Helper macro to create an SPI expander bank entry
#define GUIKIT_SPI_EXPANDER_BANK(expander_type, cs_pin, irq_pin, reset_pin, name) \
{ \
    .device_type = GUIKIT_DEVICE_SPI_EXPANDER, \
    .enabled = true, \
    .config.spi_expander = {.type = expander_type, .cs_pin = cs_pin, .irq_pin = irq_pin, .reset_pin = reset_pin}, \
    .name = name \
}

// Default ESP8266 Configuration
#define GUIKIT_HW_UNION_ESP8266_DEFAULT \
{ \
    .is_esp8266 = true, \
    .is_esp32 = false, \
    .bank_count = 3, \
    .banks = { \
        GUIKIT_SPI_DEVICE_BANK(GUIKIT_DEVICE_TFT, 15, 255, 20, "TFT"),     // D8
        GUIKIT_SPI_DEVICE_BANK(GUIKIT_DEVICE_TOUCH, 4, 255, 20, "Touch"),  // D2
        GUIKIT_SPI_DEVICE_BANK(GUIKIT_DEVICE_SD_CARD, 5, 255, 20, "SD")     // D1
    }, \
    .sck_pin = 14,   // D5
    .mosi_pin = 13,  // D7
    .miso_pin = 12,  // D6
    .max_speed_mhz = 20, \
    .display = {320, 240, 4, true}, \
    .use_sd_card = true, \
    .use_webdav = true, \
    .debug_mode = false \
}

// ESP8266 with 1MB SRAM (8x 23LC1024) - for Huge Demo
#define GUIKIT_HW_UNION_ESP8266_HUGE_DEMO \
{ \
    .is_esp8266 = true, \
    .is_esp32 = false, \
    .bank_count = 11, \
    .banks = { \
        // SPI devices
        GUIKIT_SPI_DEVICE_BANK(GUIKIT_DEVICE_TFT, 15, 255, 20, "TFT"),      // D8
        GUIKIT_SPI_DEVICE_BANK(GUIKIT_DEVICE_TOUCH, 4, 255, 20, "Touch"),   // D2
        GUIKIT_SPI_DEVICE_BANK(GUIKIT_DEVICE_SD_CARD, 5, 255, 20, "SD"),    // D1
        // SRAM banks (8x 23LC1024)
        GUIKIT_RAM_BANK(GUIKIT_RAM_SRAM, 131072, 16, "SRAM_0"),   // D0
        GUIKIT_RAM_BANK(GUIKIT_RAM_SRAM, 131072, 0, "SRAM_1"),    // D3
        GUIKIT_RAM_BANK(GUIKIT_RAM_SRAM, 131072, 1, "SRAM_2"),    // D6
        GUIKIT_RAM_BANK(GUIKIT_RAM_SRAM, 131072, 2, "SRAM_3"),    // D7
        GUIKIT_RAM_BANK(GUIKIT_RAM_SRAM, 131072, 3, "SRAM_4"),    // D8* (shared)
        GUIKIT_RAM_BANK(GUIKIT_RAM_SRAM, 131072, 9, "SRAM_5"),    // D11
        GUIKIT_RAM_BANK(GUIKIT_RAM_SRAM, 131072, 10, "SRAM_6"),   // D12
        GUIKIT_RAM_BANK(GUIKIT_RAM_SRAM, 131072, 14, "SRAM_7")    // D16
    }, \
    .sck_pin = 14,   // D5
    .mosi_pin = 13,  // D7
    .miso_pin = 12,  // D6
    .max_speed_mhz = 20, \
    .display = {320, 240, 4, true}, \
    .use_sd_card = true, \
    .use_webdav = true, \
    .debug_mode = false \
}

// ESP8266 with 2x MCP23S17 Expanders
#define GUIKIT_HW_UNION_ESP8266_EXPANDER \
{ \
    .is_esp8266 = true, \
    .is_esp32 = false, \
    .bank_count = 5, \
    .banks = { \
        // SPI devices
        GUIKIT_SPI_DEVICE_BANK(GUIKIT_DEVICE_TFT, 15, 255, 20, "TFT"),      // D8
        GUIKIT_SPI_DEVICE_BANK(GUIKIT_DEVICE_TOUCH, 4, 255, 20, "Touch"),   // D2
        GUIKIT_SPI_DEVICE_BANK(GUIKIT_DEVICE_SD_CARD, 5, 255, 20, "SD"),    // D1
        // SPI expanders
        GUIKIT_SPI_EXPANDER_BANK(GUIKIT_EXPANDER_MCP23S17, 0, 255, 255, "Expander_1"),  // D3
        GUIKIT_SPI_EXPANDER_BANK(GUIKIT_EXPANDER_MCP23S17, 1, 255, 255, "Expander_2")   // D6
    }, \
    .sck_pin = 14, \
    .mosi_pin = 13, \
    .miso_pin = 12, \
    .max_speed_mhz = 20, \
    .display = {320, 240, 4, false}, \
    .use_sd_card = true, \
    .use_webdav = true, \
    .debug_mode = false \
}

// ESP32 Premium with 8MB PSRAM + 2x MCP23S17
#define GUIKIT_HW_UNION_ESP32_PREMIUM \
{ \
    .is_esp8266 = false, \
    .is_esp32 = true, \
    .bank_count = 5, \
    .banks = { \
        // PSRAM
        GUIKIT_RAM_BANK(GUIKIT_RAM_PSRAM, 8 * 1024 * 1024, 255, "PSRAM"), \
        // SPI devices
        GUIKIT_SPI_DEVICE_BANK(GUIKIT_DEVICE_TFT, 5, 255, 40, "TFT"), \
        GUIKIT_SPI_DEVICE_BANK(GUIKIT_DEVICE_TOUCH, 21, 255, 40, "Touch"), \
        // SPI expanders
        GUIKIT_SPI_EXPANDER_BANK(GUIKIT_EXPANDER_MCP23S17, 16, 255, 255, "Expander_1"), \
        GUIKIT_SPI_EXPANDER_BANK(GUIKIT_EXPANDER_MCP23S17, 17, 255, 255, "Expander_2") \
    }, \
    .sck_pin = 18, \
    .mosi_pin = 23, \
    .miso_pin = 19, \
    .max_speed_mhz = 40, \
    .display = {320, 240, 16, true}, \
    .use_sd_card = true, \
    .use_webdav = true, \
    .debug_mode = false \
}

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Initialize config with platform defaults
 */
void guikit_hw_config_union_init(guikit_hw_config_union_t* cfg);

/**
 * Get total RAM size (internal + external SRAM/PSRAM/FRAM)
 */
uint32_t guikit_hw_union_get_total_ram(const guikit_hw_config_union_t* cfg);

/**
 * Get total external RAM size
 */
uint32_t guikit_hw_union_get_external_ram(const guikit_hw_config_union_t* cfg);

/**
 * Count number of SPI expander chips
 */
uint8_t guikit_hw_union_count_expanders(const guikit_hw_config_union_t* cfg);

/**
 * Get total GPIO from expanders
 */
uint16_t guikit_hw_union_get_expander_gpio(const guikit_hw_config_union_t* cfg);

/**
 * Get first RAM bank (convenience)
 */
const guikit_ram_config_t* guikit_hw_union_get_first_ram(const guikit_hw_config_union_t* cfg);

/**
 * Get first SPI expander (convenience)
 */
const guikit_spi_expander_config_t* guikit_hw_union_get_first_expander(const guikit_hw_config_union_t* cfg);

/**
 * Validate configuration
 */
bool guikit_hw_config_union_validate(const guikit_hw_config_union_t* cfg);

/**
 * Print configuration summary
 */
void guikit_hw_config_union_print(const guikit_hw_config_union_t* cfg);

// ============================================================================
// Inline Accessors for Type Safety
// ============================================================================

// Get RAM config from a bank (returns NULL if not RAM)
static inline const guikit_ram_config_t* guikit_bank_get_ram(const guikit_device_bank_t* bank) {
    if (GUIKIT_BANK_IS_RAM(*bank)) {
        return &bank->config.ram;
    }
    return NULL;
}

// Get SPI device config from a bank (returns NULL if not SPI device)
static inline const guikit_spi_device_config_t* guikit_bank_get_spi_device(const guikit_device_bank_t* bank) {
    if (GUIKIT_BANK_IS_SPI_DEVICE(*bank)) {
        return &bank->config.spi_device;
    }
    return NULL;
}

// Get SPI expander config from a bank (returns NULL if not expander)
static inline const guikit_spi_expander_config_t* guikit_bank_get_spi_expander(const guikit_device_bank_t* bank) {
    if (GUIKIT_BANK_IS_SPI_EXPANDER(*bank)) {
        return &bank->config.spi_expander;
    }
    return NULL;
}

// ============================================================================
// Usage Example
// ============================================================================

/**
 * Example usage of the union-based configuration:
 * 
 * guikit_hw_config_union_t config = GUIKIT_HW_UNION_ESP8266_HUGE_DEMO;
 * 
 * // Access RAM banks
 * for (int i = 0; i < config.bank_count; i++) {
 *     if (GUIKIT_BANK_IS_RAM(config.banks[i])) {
 *         const guikit_ram_config_t* ram = guikit_bank_get_ram(&config.banks[i]);
 *         printf("RAM Bank: %s, Size: %lu KB\n", config.banks[i].name, ram->size / 1024);
 *     }
 * }
 * 
 * // Access SPI expanders
 * for (int i = 0; i < config.bank_count; i++) {
 *     if (GUIKIT_BANK_IS_SPI_EXPANDER(config.banks[i])) {
 *         const guikit_spi_expander_config_t* exp = guikit_bank_get_spi_expander(&config.banks[i]);
 *         printf("Expander: %s, Type: %d\n", config.banks[i].name, exp->type);
 *     }
 * }
 * 
 * // Custom configuration
 * guikit_hw_config_union_t my_config = {0};
 * my_config.banks[0] = GUIKIT_RAM_BANK(GUIKIT_RAM_SRAM, 131072, 16, "My SRAM");
 * my_config.banks[1] = GUIKIT_SPI_EXPANDER_BANK(GUIKIT_EXPANDER_MCP23S17, 0, 255, 255, "My Expander");
 * my_config.bank_count = 2;
 */

#endif // GUIKIT_HW_CONFIG_UNION_H
